In [1]:
import json
import os
import pandas as pd

dirpath1 = '/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/xenosite/drugbank'
pathlist1 = os.listdir(dirpath1)
pathlist1 = [dirpath1+'/'+i for i in pathlist1 if i.endswith('.txt')]

# dirpath2 = '/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/xenosite/add_unnamed_files'
# pathlist2 = os.listdir(dirpath2)
# pathlist2 = [dirpath2+'/'+i for i in pathlist2 if i.endswith('.txt')]

pathlist = pathlist1# + pathlist2

smiles_new = []
models_new = []
atomscores_new = []
bondscores_new = []

# pathlist = ['unnamed (1).txt']

for path in pathlist:

    try:
        # 读取文件内容
        with open(path, 'r') as file:
            data = json.load(file)

        # 提取 SMILES
        smiles = data.get('smiles')

        # 提取每个 model 的信息
        models_info = []

        for result in data['results']:
            model = result.get('model')
            atom = result.get('atom')
            bonds = result.get('bond')

            # 保存每个 model 的详细信息
            smiles_new.append(smiles)
            models_new.append(model)
            atomscores_new.append(atom)
            bondscores_new.append(bonds)
    except:
        print(path)
    

# 打印结果

# print("SMILES:", smiles)
# for model_info in models_info:
#     print("\nModel:", model_info['model'])
#     print("Atoms:", model_info['atom'])
#     print("Bonds:", model_info['bond'])

df_new = pd.DataFrame()
df_new['substrates'] = smiles_new
df_new['enzyme'] = models_new
df_new['atomscores'] = atomscores_new
df_new['bondscores'] = bondscores_new
df_new

/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/xenosite/drugbank/unnamed - 2025-01-18T182209.460.txt
/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/xenosite/drugbank/unnamed - 2025-01-18T182157.843.txt

,substrates,enzyme,atomscores,bondscores
0,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,phase1.stable_oxygenation,"[2.682209014892578e-06, 0.0013073086738586426,...","[0.0031404495239257812, 3.4570693969726562e-06..."
1,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,phase1.unstable_oxygenation,"[3.725290298461914e-06, 4.172325134277344e-07,...","[0.0072383880615234375, 0.0004887282848358154,..."
2,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,phase1.dehydrogenation,"[3.898143768310547e-05, 5.662441253662109e-07,...","[0.0008677542209625244, 8.940696716308594e-08,..."
3,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,phase1.hydrolysis,"[4.1812658309936523e-05, 4.172325134277344e-07...","[0.0025744736194610596, 1.0758638381958008e-05..."
4,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,phase1.reduction,"[7.271766662597656e-06, 0, 0, 9.54866409301757...","[0.0417347252368927, 0, 6.258487701416016e-07,..."
...,...,...,...,...
655,O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1,phase1.stable_oxygenation,"[8.940696716308594e-08, 0.014136523008346558, ...","[0.00965571403503418, 0.00965571403503418, 0.0..."
656,O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1,phase1.unstable_oxygenation,"[7.748603820800781e-07, 4.76837158203125e-07, ...","[0.004561275243759155, 0.004561275243759155, 0..."
657,O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1,phase1.dehydrogenation,"[5.632638931274414e-06, 0.000751495361328125, ...","[0.009830445051193237, 0.009830445051193237, 4..."
658,O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1,phase1.hydrolysis,"[2.3692846298217773e-05, 4.073977470397949e-05...","[0.00977468490600586, 0.00977468490600586, 0.0..."
659,O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1,phase1.reduction,"[2.562999725341797e-06, 0, 2.562999725341797e-...","[0.04714372754096985, 0.04714372754096985, 1.4..."

In [2]:
df_new.drop_duplicates(subset=['substrates','enzyme'],keep='first',inplace=True,ignore_index=True)

In [3]:
df_new

,substrates,enzyme,atomscores,bondscores
0,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,phase1.stable_oxygenation,"[2.682209014892578e-06, 0.0013073086738586426,...","[0.0031404495239257812, 3.4570693969726562e-06..."
1,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,phase1.unstable_oxygenation,"[3.725290298461914e-06, 4.172325134277344e-07,...","[0.0072383880615234375, 0.0004887282848358154,..."
2,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,phase1.dehydrogenation,"[3.898143768310547e-05, 5.662441253662109e-07,...","[0.0008677542209625244, 8.940696716308594e-08,..."
3,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,phase1.hydrolysis,"[4.1812658309936523e-05, 4.172325134277344e-07...","[0.0025744736194610596, 1.0758638381958008e-05..."
4,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,phase1.reduction,"[7.271766662597656e-06, 0, 0, 9.54866409301757...","[0.0417347252368927, 0, 6.258487701416016e-07,..."
...,...,...,...,...
576,O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1,phase1.stable_oxygenation,"[8.940696716308594e-08, 0.014136523008346558, ...","[0.00965571403503418, 0.00965571403503418, 0.0..."
577,O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1,phase1.unstable_oxygenation,"[7.748603820800781e-07, 4.76837158203125e-07, ...","[0.004561275243759155, 0.004561275243759155, 0..."
578,O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1,phase1.dehydrogenation,"[5.632638931274414e-06, 0.000751495361328125, ...","[0.009830445051193237, 0.009830445051193237, 4..."
579,O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1,phase1.hydrolysis,"[2.3692846298217773e-05, 4.073977470397949e-05...","[0.00977468490600586, 0.00977468490600586, 0.0..."
580,O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1,phase1.reduction,"[2.562999725341797e-06, 0, 2.562999725341797e-...","[0.04714372754096985, 0.04714372754096985, 1.4..."

In [4]:
from collections import Counter


# 假设你有一个列表
example_list = df_new['substrates'].to_list()

# 使用 Counter 计数
element_count = Counter(example_list)

# 输出结果
for key, count in element_count.items():
    if count < 6:
        print(key)

O=c1[nH]c(=O)n(C2CC(O)C(COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O2)cc1F
N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2)cc1
CNCC(=O)OCc1cccnc1N(C)C(=O)OC(C)[n+]1cnn(CC(O)(c2cc(F)ccc2F)C(C)c2nc(-c3ccc(C#N)cc3)cs2)c1
O=c1[nH]c(=O)n(C2OC(COP(=O)(O)O)C(O)C2O)cc1F
COc1nc(N)nc2[nH]cnc12
COc1cc2c(c(OC)c1OC)-c1ccc(OC)c(=O)cc1C(NC(C)=O)CC2
CC1CC2C3CC(F)C4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(OC(=O)c1ccco1)C(=O)SCF
CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2
O=C(O)c1cc(N=Nc2ccc(O)c(C(=O)O)c2)ccc1O
NC(=O)CNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2)cc1
COc1ccc(CC(C)NCCOc2ccccc2O)cc1S(N)(=O)=O
CC1CCC2C(C)C(O)OC3OC4(C)CCC1C32OO4
CCCCCC(O)C=CC1C(O)CC(=O)C1CCCCCCC(=O)O
NC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4=O)cc3)n2)cc1
OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3ccccc3)(CC1)CC2
O=C(O)CC(O)CC(O)C=Cc1c(C2CC2)nc2ccccc2c1-c1ccc(F)cc1
O=c1[nH]c(=O)n(C2CC(O)C(COP(=O)(O)O)O2)cc1F
CC(CCC(=O)O)C1CCC2C3C(O)CC4CC(O)CCC4(C)C3CCC12C
CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5CCOCC5)ccc34)cc2)no1
Cc1c(OCC(F)(F)F)ccnc1CS(=O)c1nc2ccc(OC3OC(C(=O)O)C(O)C(O)C3O)cc2[nH]1
O=C1CN=C(c2ccccc2Cl)c2cc([N+](=O)[O-])ccc2N1
Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2
O=c1[nH]c(=O)c2[nH]cnc2[nH]1
CN(C)CCc1c[nH]c2cc(O)c(Cn3cncn3)cc12
COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)CC(O)(C(=O)CO)CC3OC1CC(N)C(O)C(C)O1
CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccccn3)c2)c(Cl)c1
Clc1ccc2c(c1)N=C(N1CCNCC1)c1ccccc1N2
O=C1CC(=O)N(c2ccccc2)c2cc(Cl)ccc2N1
O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1

In [6]:
from rdkit import Chem
def canonicalsmiles(smiles):
    mol = Chem.MolFromSmiles(smiles)
    smi_new = Chem.MolToSmiles(mol, isomericSmiles=False)
    return smi_new

In [7]:
# 输出的结果会失去立体构象
smiles_now = list(set(df_new['substrates'].to_list()))
smiles_now = list(map(canonicalsmiles,smiles_now))

df = pd.read_csv('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/GNN-SOM-master/123_site_from_smiles.csv')
smiles_shouldbe = df['substrate'].to_list()
smiles_shouldbe = list(map(canonicalsmiles,smiles_shouldbe))

smiles_out = [i for i in smiles_shouldbe if i not in smiles_now]
for i in smiles_out:
    print(i)

In [8]:
df_new.to_pickle('xenosite_results_drugbank.pickle')

In [11]:
df =  pd.read_pickle('xenosite_results_drugbank.pickle')
df

,substrates,enzyme,atomscores,bondscores
0,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,phase1.stable_oxygenation,"[2.682209014892578e-06, 0.0013073086738586426,...","[0.0031404495239257812, 3.4570693969726562e-06..."
1,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,phase1.unstable_oxygenation,"[3.725290298461914e-06, 4.172325134277344e-07,...","[0.0072383880615234375, 0.0004887282848358154,..."
2,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,phase1.dehydrogenation,"[3.898143768310547e-05, 5.662441253662109e-07,...","[0.0008677542209625244, 8.940696716308594e-08,..."
3,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,phase1.hydrolysis,"[4.1812658309936523e-05, 4.172325134277344e-07...","[0.0025744736194610596, 1.0758638381958008e-05..."
4,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,phase1.reduction,"[7.271766662597656e-06, 0, 0, 9.54866409301757...","[0.0417347252368927, 0, 6.258487701416016e-07,..."
...,...,...,...,...
576,O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1,phase1.stable_oxygenation,"[8.940696716308594e-08, 0.014136523008346558, ...","[0.00965571403503418, 0.00965571403503418, 0.0..."
577,O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1,phase1.unstable_oxygenation,"[7.748603820800781e-07, 4.76837158203125e-07, ...","[0.004561275243759155, 0.004561275243759155, 0..."
578,O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1,phase1.dehydrogenation,"[5.632638931274414e-06, 0.000751495361328125, ...","[0.009830445051193237, 0.009830445051193237, 4..."
579,O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1,phase1.hydrolysis,"[2.3692846298217773e-05, 4.073977470397949e-05...","[0.00977468490600586, 0.00977468490600586, 0.0..."
580,O=S1(=O)CCN(CN2CCS(=O)(=O)NC2)CN1,phase1.reduction,"[2.562999725341797e-06, 0, 2.562999725341797e-...","[0.04714372754096985, 0.04714372754096985, 1.4..."

In [12]:
df =  pd.read_pickle('xenosite_results_drugbank.pickle')
atomscores = df['atomscores'].to_list()

# 使用字典推导式生成字典
atomscores = [{idx: score for idx, score in enumerate(i)} for i in atomscores]
df['atomscores'] = atomscores

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result
def assign_ranks(atom_scores):
    # 按分数降序排序，并获取排序后的原子序号
    sorted_atoms = sorted(atom_scores.items(), key=lambda x: x[1], reverse=True)
    
    # 创建一个字典，保存原子序号对应的排名
    rank_dict = {}
    for rank, (atom, _) in enumerate(sorted_atoms):
        rank_dict[atom] = rank + 1
    
    # 保持原子序号从小到大的顺序，并更新为对应的排名
    ranked_atoms = {atom: rank_dict[atom] for atom in sorted(atom_scores)}
    
    return ranked_atoms

atomscores = df['atomscores'].to_list()
atomscores = list(map(assign_ranks,atomscores))
df['atomscores'] = atomscores
# df.to_pickle('xenosite_results_withrank.pickle')
# 示例
result = group_by_column_to_dict(df, 'substrates', 'atomscores')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2': {0: 42, 1: 63, 2: 57, 3: 15, 4: 95, 5: 38, 6: 48, 7: 101, 8: 96, 9: 51, 10: 81, 11: 91, 12: 40, 13: 42, 14: 28, 15: 47, 16: 85, 17: 113, 18: 20, 19: 59, 20: 92, 21: 58, 22: 18}, 'CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(I)cc4F)n(C)c(=O)c(C)c32)c1': {0: 71, 1: 119, 2: 88, 3: 19, 4: 157, 5: 76, 6: 65, 7: 93, 8: 151, 9: 91, 10: 173, 11: 104, 12: 73, 13: 82, 14: 68, 15: 74, 16: 166, 17: 100, 18: 176, 19: 168, 20: 23, 21: 171, 22: 67, 23: 56, 24: 156, 25: 182, 26: 86, 27: 170, 28: 191, 29: 81, 30: 92, 31: 190, 32: 88, 33: 185, 34: 83, 35: 163, 36: 120}, 'CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c2=O)cc1O': {0: 47, 1: 145, 2: 54, 3: 60, 4: 133, 5: 87, 6: 135, 7: 155, 8: 63, 9: 69, 10: 75, 11: 143, 12: 24, 13: 101, 14: 75, 15: 142, 16: 90, 17: 37, 18: 145, 19: 53, 20: 47, 21: 64, 22: 56, 23: 141, 24: 133, 25: 71, 26: 81, 27: 152, 28: 32}, 'CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5CCOCC5)ccc34)cc2)no1': {0: 12, 1: 40, 2: 13, 3: 14, 4: 37, 5: 36, 6: 35, 7: 1, 8: 34, 9: 8, 10: 4, 11: 38, 12: 27, 13: 25, 14: 39, 15: 22, 16: 21, 17: 7, 18: 16, 19: 5, 20: 33, 21: 24, 22: 32, 23: 31, 24: 15, 25: 17, 26: 20, 27: 6, 28: 18, 29: 9, 30: 2, 31: 10, 32: 19, 33: 23, 34: 30, 35: 29, 36: 26, 37: 28, 38: 3, 39: 11}, 'CC(C=CC12OC1(C)CCCC2(C)C)=CC=CC(C)=CC(=O)O': {0: 49, 1: 91, 2: 68, 3: 67, 4: 115, 5: 48, 6: 124, 7: 71, 8: 63, 9: 61, 10: 69, 11: 134, 12: 66, 13: 72, 14: 42, 15: 51, 16: 48, 17: 89, 18: 64, 19: 34, 20: 98, 21: 91, 22: 41}, 'CC(C=CC1=C(C)C(=O)CCC1(C)C)=CC=CC(C)=CC(=O)O': {0: 53, 1: 91, 2: 57, 3: 70, 4: 100, 5: 98, 6: 67, 7: 103, 8: 64, 9: 63, 10: 53, 11: 133, 12: 57, 13: 63, 14: 42, 15: 51, 16: 47, 17: 93, 18: 64, 19: 31, 20: 97, 21: 112, 22: 47}, 'CC(C=CC1=C(C)CCCC1(C)C)=CC=CC(C)=CC(=O)O': {0: 51, 1: 88, 2: 56, 3: 70, 4: 101, 5: 100, 6: 66, 7: 60, 8: 54, 9: 60, 10: 128, 11: 58, 12: 64, 13: 40, 14: 49, 15: 47, 16: 90, 17: 66, 18: 31, 19: 97, 20: 96, 21: 46}, 'CC(CCC(=O)O)C1CCC2C3C(=O)CC4CC(O)CCC4(C)C3CCC12C': {0: 63, 1: 93, 2: 69, 3: 69, 4: 107, 5: 111, 6: 52, 7: 80, 8: 64, 9: 69, 10: 64, 11: 103, 12: 135, 13: 84, 14: 105, 15: 76, 16: 75, 17: 40, 18: 28, 19: 63, 20: 87, 21: 159, 22: 93, 23: 97, 24: 102, 25: 89, 26: 163, 27: 96}, 'CC(CCC(=O)O)C1CCC2C3C(O)CC4CC(O)CCC4(C)C3CCC12C': {0: 7, 1: 27, 2: 15, 3: 20, 4: 18, 5: 4, 6: 3, 7: 21, 8: 8, 9: 5, 10: 12, 11: 25, 12: 26, 13: 1, 14: 17, 15: 22, 16: 16, 17: 19, 18: 2, 19: 13, 20: 11, 21: 28, 22: 10, 23: 24, 24: 14, 25: 9, 26: 23, 27: 6}, 'CC(N)Cc1ccc(O)cc1': {0: 30, 1: 35, 2: 14, 3: 36, 4: 60, 5: 41, 6: 23, 7: 65, 8: 16, 9: 29, 10: 47}, 'CC(N)Cc1ccccc1': {0: 33, 1: 37, 2: 10, 3: 39, 4: 60, 5: 37, 6: 23, 7: 19, 8: 29, 9: 43}, 'CC(O)C1C(=O)N2C(C(=O)O)=C(SC3CNC(C(=O)Nc4cccc(C(=O)O)c4)C3)C(C)C12': {0: 82, 1: 74, 2: 33, 3: 112, 4: 154, 5: 109, 6: 69, 7: 153, 8: 151, 9: 142, 10: 72, 11: 138, 12: 48, 13: 102, 14: 94, 15: 31, 16: 98, 17: 140, 18: 107, 19: 41, 20: 180, 21: 81, 22: 73, 23: 78, 24: 159, 25: 137, 26: 133, 27: 67, 28: 87, 29: 83, 30: 114, 31: 93, 32: 131}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncc(O)cn3)CC2)C(=O)C1': {0: 58, 1: 141, 2: 65, 3: 71, 4: 122, 5: 82, 6: 58, 7: 85, 8: 75, 9: 78, 10: 82, 11: 27, 12: 67, 13: 74, 14: 38, 15: 147, 16: 80, 17: 79, 18: 146, 19: 37, 20: 86, 21: 88, 22: 84, 23: 79, 24: 140, 25: 88, 26: 91}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1': {0: 62, 1: 138, 2: 69, 3: 71, 4: 121, 5: 81, 6: 45, 7: 84, 8: 73, 9: 75, 10: 76, 11: 26, 12: 69, 13: 75, 14: 35, 15: 143, 16: 70, 17: 76, 18: 75, 19: 83, 20: 76, 21: 85, 22: 81, 23: 139, 24: 87, 25: 91}, 'CC1(C)CC(=O)N(CCCCN2CCN(c3ncccn3)CC2)C(=O)C1O': {0: 65, 1: 143, 2: 72, 3: 78, 4: 129, 5: 88, 6: 50, 7: 92, 8: 79, 9: 83, 10: 84, 11: 30, 12: 79, 13: 82, 14: 37, 15: 149, 16: 75, 17: 77, 18: 81, 19: 84, 20: 81, 21: 92, 22: 91, 23: 135, 24: 94, 25: 85, 26: 33}, 'CC12CCC(O)CC1=CCC1C2CCC2(C)C(c3cccnc3)=CCC12': {0: 70, 1: 139, 2: 66, 3: 50, 4: 44, 5: 30, 6: 76, 7: 120, 8: 65, 9: 83, 10: 85, 11: 90, 12: 83, 13: 69, 14: 145, 15: 77, 16: 111, 17: 145, 18: 59, 19: 55, 20: 80, 21: 57, 22: 103, 23: 64, 24: 79, 25: 61}, 'CC1CC2C3CC(F)C4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(OC(=O)c1ccco1)C(=O)O': {0: 62, 1: 85, 2: 72, 3: 85, 4: 112, 5: 89, 6: 109, 7: 157, 8: 130, 9: 68, 10: 126, 11: 68, 12: 45, 13: 62, 14: 177, 15: 73, 16: 182, 17: 182, 18: 105, 19: 32, 20: 97, 21: 182, 22: 95, 23: 189, 24: 99, 25: 126, 26: 94, 27: 169, 28: 74, 29: 81, 30: 95, 31: 103, 32: 132, 33: 156, 34: 67}, 'CC1CC2C3CC(F)C4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(OC(=O)c1ccco1)C(=O)SCF': {0: 9, 1: 30, 2: 3, 3: 10, 4: 25, 5: 15, 6: 32, 7: 21, 8: 34, 9: 22, 10: 19, 11: 2, 12: 13, 13: 29, 14: 36, 15: 11, 16: 35, 17: 27, 18: 28, 19: 1, 20: 8, 21: 26, 22: 6, 23: 24, 24: 16, 25: 31, 26: 4, 27: 37, 28: 20, 29: 12, 30: 18, 31: 7, 32: 33, 33: 5, 34: 17, 35: 23, 36: 14}, 'CC1CCC2C(C)C(O)OC3OC4(C)CCC1C32OO4': {0: 36, 1: 43, 2: 41, 3: 54, 4: 56, 5: 36, 6: 45, 7: 30, 8: 19, 9: 49, 10: 45, 11: 64, 12: 92, 13: 50, 14: 49, 15: 70, 16: 72, 17: 100, 18: 57, 19: 42}, 'CC1OC(n2cc(F)c(N)nc2=O)C(O)C1O': {0: 48, 1: 36, 2: 52, 3: 49, 4: 49, 5: 64, 6: 89, 7: 89, 8: 85, 9: 22, 10: 55, 11: 95, 12: 60, 13: 44, 14: 24, 15: 35, 16: 22}, 'CCC(=O)N1CCC(Nc2ncnc3c2CN(c2cnc(O)c(C(F)(F)F)c2)CC3)C1': {0: 48, 1: 65, 2: 101, 3: 81, 4: 44, 5: 59, 6: 50, 7: 72, 8: 36, 9: 138, 10: 87, 11: 102, 12: 72, 13: 136, 14: 139, 15: 77, 16: 43, 17: 154, 18: 100, 19: 55, 20: 152, 21: 44, 22: 141, 23: 166, 24: 159, 25: 165, 26: 171, 27: 78, 28: 80, 29: 78, 30: 83}, 'CCC(=O)N1CCC(Nc2ncnc3c2CN(c2cnc(OC)c(C(F)(F)F)c2)CC3)C1': {0: 48, 1: 67, 2: 103, 3: 83, 4: 38, 5: 61, 6: 55, 7: 76, 8: 33, 9: 146, 10: 87, 11: 105, 12: 83, 13: 136, 14: 140, 15: 82, 16: 36, 17: 156, 18: 104, 19: 59, 20: 162, 21: 74, 22: 79, 23: 148, 24: 171, 25: 161, 26: 167, 27: 173, 28: 79, 29: 85, 30: 84, 31: 87}, 'CCC(C)n1ncn(-c2ccc(N3CCN(c4ccc(OCC5COC(Cn6cncn6)(c6ccc(Cl)cc6Cl)O5)cc4)CC3)cc2)c1=O': {0: 71, 1: 84, 2: 99, 3: 78, 4: 112, 5: 134, 6: 173, 7: 108, 8: 227, 9: 146, 10: 126, 11: 238, 12: 29, 13: 111, 14: 102, 15: 18, 16: 236, 17: 127, 18: 106, 19: 234, 20: 97, 21: 133, 22: 134, 23: 115, 24: 97, 25: 248, 26: 134, 27: 144, 28: 175, 29: 127, 30: 175, 31: 160, 32: 235, 33: 167, 34: 140, 35: 225, 36: 245, 37: 158, 38: 253, 39: 259, 40: 104, 41: 112, 42: 152, 43: 130, 44: 141, 45: 160, 46: 181, 47: 257, 48: 133}, 'CCC(c1cc(O)cc(O)c1)C(C)CN(C)C': {0: 37, 1: 44, 2: 58, 3: 90, 4: 51, 5: 89, 6: 20, 7: 38, 8: 95, 9: 26, 10: 57, 11: 54, 12: 58, 13: 61, 14: 30, 15: 52, 16: 58}, 'CCC(c1cccc(O)c1)C(C)CN(C)C': {0: 38, 1: 46, 2: 50, 3: 89, 4: 56, 5: 44, 6: 33, 7: 88, 8: 20, 9: 54, 10: 54, 11: 56, 12: 60, 13: 20, 14: 51, 15: 57}, 'CCC1C(=O)OCC1Cc1cncn1C': {0: 34, 1: 35, 2: 44, 3: 63, 4: 49, 5: 45, 6: 49, 7: 37, 8: 47, 9: 85, 10: 59, 11: 31, 12: 59, 13: 36, 14: 47}, 'CCCCCC(=O)C=CC1C(O)CC(=O)C1CCCCCCC(=O)O': {0: 48, 1: 54, 2: 75, 3: 62, 4: 92, 5: 103, 6: 77, 7: 71, 8: 74, 9: 60, 10: 65, 11: 32, 12: 76, 13: 126, 14: 85, 15: 75, 16: 85, 17: 93, 18: 87, 19: 86, 20: 66, 21: 78, 22: 110, 23: 112, 24: 58}, 'CCCCCC(=O)CCC1C(O)CC(=O)C1CCCCCCC(=O)O': {0: 39, 1: 45, 2: 67, 3: 58, 4: 91, 5: 101, 6: 81, 7: 108, 8: 85, 9: 51, 10: 74, 11: 30, 12: 81, 13: 112, 14: 85, 15: 86, 16: 84, 17: 94, 18: 79, 19: 83, 20: 67, 21: 74, 22: 108, 23: 108, 24: 59}, 'CCCCCC(O)C=CC1C(O)CC(=O)C1CCCCCCC(=O)O': {0: 6, 1: 10, 2: 16, 3: 11, 4: 21, 5: 24, 6: 1, 7: 13, 8: 23, 9: 14, 10: 22, 11: 2, 12: 8, 13: 25, 14: 4, 15: 15, 16: 9, 17: 17, 18: 18, 19: 19, 20: 7, 21: 20, 22: 12, 23: 5, 24: 3}, 'CCCCCOC(=O)Nc1nc(=O)n(C2OC(C)C(O)C2O)cc1F': {0: 49, 1: 57, 2: 64, 3: 73, 4: 69, 5: 77, 6: 108, 7: 84, 8: 31, 9: 121, 10: 89, 11: 132, 12: 90, 13: 71, 14: 74, 15: 73, 16: 61, 17: 78, 18: 48, 19: 29, 20: 63, 21: 31, 22: 105, 23: 137, 24: 136}, 'CCCc1nc(C)c2c(=O)nc(-c3cc(S(=O)(=O)N4CCN(CC)CC4)ccc3OCC)[nH]n12': {0: 60, 1: 54, 2: 75, 3: 153, 4: 84, 5: 152, 6: 87, 7: 176, 8: 166, 9: 91, 10: 104, 11: 173, 12: 170, 13: 111, 14: 164, 15: 94, 16: 105, 17: 111, 18: 43, 19: 87, 20: 84, 21: 30, 22: 78, 23: 79, 24: 92, 25: 97, 26: 96, 27: 122, 28: 179, 29: 70, 30: 96, 31: 92, 32: 71, 33: 124}, 'CCN(CC)C(=O)C1(c2ccccc2)CC1CN': {0: 40, 1: 52, 2: 29, 3: 58, 4: 48, 5: 91, 6: 58, 7: 103, 8: 98, 9: 63, 10: 40, 11: 33, 12: 46, 13: 69, 14: 62, 15: 56, 16: 67, 17: 13}, 'CCNC1CN(CCCOC)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': {0: 54, 1: 57, 2: 22, 3: 71, 4: 58, 5: 35, 6: 62, 7: 64, 8: 38, 9: 46, 10: 51, 11: 79, 12: 86, 13: 92, 14: 118, 15: 105, 16: 107, 17: 72, 18: 30, 19: 84, 20: 90, 21: 105, 22: 130}, 'CCOC1CCN(Cc2c(OC)cc(C)c3[nH]ccc23)C(c2ccc(C(=O)O)cc2)C1': {0: 57, 1: 48, 2: 59, 3: 79, 4: 73, 5: 76, 6: 29, 7: 95, 8: 152, 9: 161, 10: 71, 11: 86, 12: 79, 13: 152, 14: 80, 15: 166, 16: 34, 17: 107, 18: 77, 19: 167, 20: 93, 21: 166, 22: 87, 23: 70, 24: 154, 25: 121, 26: 122, 27: 50, 28: 76, 29: 94, 30: 95}, 'CCOc1ccc(O)cc1OCCNC(C)Cc1ccc(OC)c(S(N)(=O)=O)c1': {0: 68, 1: 72, 2: 59, 3: 140, 4: 79, 5: 61, 6: 145, 7: 32, 8: 71, 9: 147, 10: 72, 11: 84, 12: 85, 13: 23, 14: 75, 15: 70, 16: 80, 17: 152, 18: 97, 19: 84, 20: 154, 21: 70, 22: 86, 23: 143, 24: 94, 25: 42, 26: 109, 27: 115, 28: 101}, 'CN(C)CCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 37, 1: 15, 2: 43, 3: 57, 4: 63, 5: 63, 6: 113, 7: 114, 8: 65, 9: 37, 10: 112, 11: 118, 12: 43, 13: 71, 14: 41, 15: 50, 16: 119, 17: 82, 18: 118, 19: 107, 20: 38, 21: 78, 22: 97, 23: 119}, 'CN(C)CCc1c[nH]c2cc(O)c(Cn3cncn3)cc12': {0: 8, 1: 7, 2: 9, 3: 11, 4: 10, 5: 20, 6: 16, 7: 3, 8: 18, 9: 17, 10: 19, 11: 1, 12: 21, 13: 5, 14: 6, 15: 13, 16: 2, 17: 12, 18: 4, 19: 15, 20: 14}, 'CN(C)CCc1c[nH]c2ccc(Cn3cncn3)cc12': {0: 35, 1: 18, 2: 41, 3: 53, 4: 51, 5: 98, 6: 68, 7: 27, 8: 107, 9: 48, 10: 50, 11: 108, 12: 54, 13: 53, 14: 76, 15: 55, 16: 74, 17: 73, 18: 61, 19: 110}, 'CN1C(=O)CC(=O)N(c2ccc(O)cc2)c2cc(Cl)ccc21': {0: 52, 1: 25, 2: 91, 3: 56, 4: 53, 5: 92, 6: 64, 7: 27, 8: 109, 9: 58, 10: 35, 11: 98, 12: 21, 13: 41, 14: 64, 15: 117, 16: 72, 17: 103, 18: 118, 19: 45, 20: 52, 21: 125}, 'CN1CCC(NC(=O)Nc2ccc(C#N)cc2)CC1c1nc2ccccc2[nH]1': {0: 82, 1: 31, 2: 72, 3: 68, 4: 87, 5: 33, 6: 133, 7: 94, 8: 31, 9: 139, 10: 91, 11: 70, 12: 135, 13: 122, 14: 57, 15: 76, 16: 99, 17: 74, 18: 90, 19: 149, 20: 69, 21: 156, 22: 58, 23: 80, 24: 74, 25: 59, 26: 157, 27: 50}, 'CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)c3)cc2)ccn1': {0: 66, 1: 24, 2: 111, 3: 75, 4: 141, 5: 75, 6: 138, 7: 69, 8: 138, 9: 51, 10: 61, 11: 141, 12: 26, 13: 129, 14: 88, 15: 28, 16: 143, 17: 72, 18: 62, 19: 139, 20: 145, 21: 134, 22: 174, 23: 158, 24: 164, 25: 170, 26: 74, 27: 67, 28: 57, 29: 90, 30: 106, 31: 52}, 'CNCC(=O)OCc1cccnc1N(C)C(=O)OC(C)[n+]1cnn(CC(O)(c2cc(F)ccc2F)C(C)c2nc(-c3ccc(C#N)cc3)cs2)c1': {0: 63, 1: 35, 2: 69, 3: 119, 4: 123, 5: 115, 6: 88, 7: 176, 8: 79, 9: 73, 10: 103, 11: 116, 12: 194, 13: 51, 14: 106, 15: 154, 16: 151, 17: 124, 18: 102, 19: 79, 20: 105, 21: 145, 22: 134, 23: 127, 24: 99, 25: 216, 26: 52, 27: 193, 28: 120, 29: 200, 30: 227, 31: 87, 32: 102, 33: 211, 34: 237, 35: 103, 36: 96, 37: 205, 38: 136, 39: 208, 40: 204, 41: 99, 42: 106, 43: 206, 44: 166, 45: 65, 46: 113, 47: 108, 48: 120, 49: 151, 50: 169}, 'CNCCCC1(c2ccc(F)cc2)OCc2cc(C#N)ccc21': {0: 39, 1: 14, 2: 53, 3: 56, 4: 60, 5: 113, 6: 104, 7: 63, 8: 33, 9: 107, 10: 111, 11: 39, 12: 71, 13: 39, 14: 46, 15: 114, 16: 74, 17: 112, 18: 100, 19: 37, 20: 67, 21: 89, 22: 115}, 'COc1c(OCCCN2CCOCC2)ccc2c1N=C(NC(=O)c1cnc(N)nc1)N1CCN=C21': {0: 89, 1: 77, 2: 162, 3: 161, 4: 92, 5: 87, 6: 90, 7: 84, 8: 36, 9: 80, 10: 56, 11: 68, 12: 62, 13: 88, 14: 112, 15: 102, 16: 172, 17: 166, 18: 122, 19: 183, 20: 45, 21: 145, 22: 134, 23: 185, 24: 113, 25: 115, 26: 184, 27: 23, 28: 122, 29: 122, 30: 90, 31: 85, 32: 103, 33: 31, 34: 194}, 'COc1cc(C)c2[nH]ccc2c1CN1CCC(O)CC1c1ccc(C(=O)O)cc1': {0: 72, 1: 66, 2: 145, 3: 70, 4: 132, 5: 69, 6: 150, 7: 35, 8: 92, 9: 81, 10: 157, 11: 147, 12: 94, 13: 28, 14: 79, 15: 58, 16: 53, 17: 28, 18: 80, 19: 84, 20: 151, 21: 78, 22: 68, 23: 146, 24: 110, 25: 129, 26: 48, 27: 74, 28: 86}, 'COc1cc(Nc2c(C#N)cnc3cc(OCCCN4CCN(C)CC4)c(OC)cc23)c(Cl)cc1Cl': {0: 73, 1: 68, 2: 140, 3: 73, 4: 162, 5: 16, 6: 153, 7: 164, 8: 136, 9: 68, 10: 107, 11: 88, 12: 163, 13: 103, 14: 153, 15: 79, 16: 85, 17: 90, 18: 88, 19: 33, 20: 87, 21: 82, 22: 31, 23: 89, 24: 89, 25: 96, 26: 172, 27: 71, 28: 104, 29: 115, 30: 187, 31: 182, 32: 183, 33: 109, 34: 168, 35: 189}, 'COc1cc(OC)cc(N(CCNC(C)C)c2ccc3ncc(-c4cnn(C)c4)nc3c2)c1': {0: 73, 1: 65, 2: 151, 3: 74, 4: 157, 5: 71, 6: 81, 7: 85, 8: 168, 9: 49, 10: 90, 11: 80, 12: 27, 13: 69, 14: 57, 15: 63, 16: 173, 17: 96, 18: 74, 19: 175, 20: 57, 21: 129, 22: 169, 23: 168, 24: 118, 25: 113, 26: 110, 27: 82, 28: 101, 29: 85, 30: 181, 31: 84, 32: 91}, 'COc1cc2c(c(OC)c1OC)-c1ccc(OC)c(=O)cc1C(NC(C)=O)CC2': {0: 7, 1: 9, 2: 27, 3: 20, 4: 23, 5: 19, 6: 28, 7: 13, 8: 5, 9: 29, 10: 12, 11: 6, 12: 14, 13: 21, 14: 17, 15: 25, 16: 10, 17: 8, 18: 24, 19: 3, 20: 22, 21: 18, 22: 15, 23: 2, 24: 26, 25: 16, 26: 1, 27: 11, 28: 4}, 'COc1cc2c(cc1OC)C1CC(O)C(CC(C)C)CN1CC2': {0: 58, 1: 54, 2: 114, 3: 75, 4: 112, 5: 117, 6: 84, 7: 121, 8: 61, 9: 66, 10: 74, 11: 69, 12: 65, 13: 24, 14: 64, 15: 67, 16: 67, 17: 57, 18: 63, 19: 80, 20: 32, 21: 61, 22: 71}, 'COc1ccc(CC(C)NCCOc2ccccc2O)cc1S(N)(=O)=O': {0: 5, 1: 11, 2: 24, 3: 19, 4: 18, 5: 25, 6: 12, 7: 13, 8: 7, 9: 2, 10: 15, 11: 10, 12: 4, 13: 23, 14: 14, 15: 8, 16: 6, 17: 9, 18: 22, 19: 1, 20: 21, 21: 26, 22: 20, 23: 3, 24: 16, 25: 17}, 'COc1ccc2nc(S(=O)Cc3ncc(C)c(OC)c3C)[nH]c2c1': {0: 47, 1: 48, 2: 103, 3: 49, 4: 56, 5: 120, 6: 45, 7: 104, 8: 55, 9: 66, 10: 53, 11: 116, 12: 52, 13: 76, 14: 116, 15: 59, 16: 115, 17: 55, 18: 66, 19: 122, 20: 65, 21: 30, 22: 130, 23: 52}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)CC(O)(C(=O)CO)CC3': {0: 59, 1: 60, 2: 135, 3: 57, 4: 65, 5: 69, 6: 121, 7: 132, 8: 102, 9: 82, 10: 145, 11: 136, 12: 40, 13: 121, 14: 137, 15: 144, 16: 46, 17: 121, 18: 104, 19: 80, 20: 73, 21: 171, 22: 25, 23: 69, 24: 81, 25: 75, 26: 19, 27: 68, 28: 73}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)CC(O)(C(=O)CO)CC3OC1CC(N)C(O)C(C)O1': {0: 10, 1: 11, 2: 30, 3: 15, 4: 14, 5: 21, 6: 27, 7: 31, 8: 28, 9: 7, 10: 38, 11: 32, 12: 3, 13: 35, 14: 34, 15: 37, 16: 2, 17: 36, 18: 26, 19: 6, 20: 18, 21: 39, 22: 5, 23: 29, 24: 8, 25: 16, 26: 1, 27: 19, 28: 23, 29: 17, 30: 25, 31: 20, 32: 22, 33: 9, 34: 33, 35: 4, 36: 24, 37: 13, 38: 12}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)CC(O)(C(O)CO)CC3': {0: 63, 1: 64, 2: 138, 3: 65, 4: 70, 5: 69, 6: 123, 7: 126, 8: 103, 9: 87, 10: 146, 11: 137, 12: 47, 13: 117, 14: 135, 15: 144, 16: 51, 17: 130, 18: 108, 19: 83, 20: 79, 21: 171, 22: 29, 23: 64, 24: 25, 25: 74, 26: 18, 27: 71, 28: 73}, 'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)CC(O)(C(O)CO)CC3OC1CC(N)C(O)C(C)O1': {0: 101, 1: 93, 2: 181, 3: 90, 4: 98, 5: 109, 6: 168, 7: 180, 8: 160, 9: 125, 10: 195, 11: 199, 12: 72, 13: 181, 14: 192, 15: 208, 16: 65, 17: 198, 18: 161, 19: 119, 20: 116, 21: 229, 22: 47, 23: 94, 24: 38, 25: 100, 26: 30, 27: 119, 28: 121, 29: 110, 30: 83, 31: 98, 32: 115, 33: 55, 34: 93, 35: 36, 36: 83, 37: 112, 38: 106}, 'COc1nc(N)nc2[nH]cnc12': {0: 26, 1: 27, 2: 45, 3: 32, 4: 51, 5: 6, 6: 29, 7: 49, 8: 16, 9: 35, 10: 16, 11: 58}, 'COc1nc(N)nc2c1ncn2C1OC(CO)C(O)C1O': {0: 56, 1: 64, 2: 103, 3: 72, 4: 108, 5: 27, 6: 82, 7: 114, 8: 119, 9: 57, 10: 93, 11: 60, 12: 71, 13: 64, 14: 47, 15: 64, 16: 19, 17: 45, 18: 31, 19: 57, 20: 33}, 'COc1nc2ccc(Br)cc2cc1C(c1ccccc1)C(O)(CCN(C)C)c1cccc2ccccc12': {0: 80, 1: 80, 2: 176, 3: 93, 4: 182, 5: 84, 6: 63, 7: 175, 8: 173, 9: 76, 10: 179, 11: 138, 12: 187, 13: 97, 14: 173, 15: 108, 16: 67, 17: 53, 18: 73, 19: 114, 20: 194, 21: 42, 22: 101, 23: 92, 24: 33, 25: 81, 26: 87, 27: 192, 28: 150, 29: 109, 30: 66, 31: 182, 32: 70, 33: 65, 34: 84, 35: 100, 36: 199}, 'COc1ncc(N2CCc3ncnc(N)c3C2)cc1C(F)(F)F': {0: 41, 1: 47, 2: 99, 3: 37, 4: 61, 5: 97, 6: 19, 7: 42, 8: 43, 9: 91, 10: 47, 11: 65, 12: 54, 13: 104, 14: 15, 15: 100, 16: 54, 17: 50, 18: 99, 19: 122, 20: 117, 21: 123, 22: 129}, 'CS(=O)(=O)c1ccc(C(=O)Nc2cc(O)c(Cl)c(-c3ccccn3)c2)c(Cl)c1': {0: 54, 1: 53, 2: 73, 3: 79, 4: 117, 5: 67, 6: 59, 7: 128, 8: 99, 9: 69, 10: 18, 11: 139, 12: 61, 13: 132, 14: 30, 15: 136, 16: 142, 17: 127, 18: 140, 19: 60, 20: 40, 21: 41, 22: 84, 23: 50, 24: 67, 25: 138, 26: 152, 27: 81}, 'CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccc(O)cn3)c2)c(Cl)c1': {0: 52, 1: 51, 2: 71, 3: 77, 4: 116, 5: 64, 6: 58, 7: 129, 8: 100, 9: 69, 10: 19, 11: 123, 12: 53, 13: 69, 14: 129, 15: 139, 16: 131, 17: 140, 18: 59, 19: 37, 20: 136, 21: 29, 22: 84, 23: 51, 24: 78, 25: 141, 26: 151, 27: 80}, 'CS(=O)(=O)c1ccc(C(=O)Nc2ccc(Cl)c(-c3ccccn3)c2)c(Cl)c1': {0: 7, 1: 15, 2: 5, 3: 6, 4: 22, 5: 14, 6: 16, 7: 26, 8: 21, 9: 3, 10: 2, 11: 20, 12: 17, 13: 13, 14: 23, 15: 10, 16: 27, 17: 24, 18: 12, 19: 4, 20: 9, 21: 8, 22: 1, 23: 19, 24: 25, 25: 11, 26: 18}, 'Cc1c(=O)n(C)c(Nc2ccc(I)cc2F)c2c(=O)n(C3CC3)c(=O)n(-c3ccc(O)c(N)c3)c12': {0: 58, 1: 142, 2: 149, 3: 79, 4: 81, 5: 72, 6: 147, 7: 29, 8: 155, 9: 67, 10: 59, 11: 135, 12: 160, 13: 59, 14: 153, 15: 168, 16: 164, 17: 153, 18: 92, 19: 74, 20: 83, 21: 72, 22: 78, 23: 175, 24: 111, 25: 85, 26: 171, 27: 106, 28: 61, 29: 177, 30: 31, 31: 164, 32: 19, 33: 86, 34: 165}, 'Cc1c(OCC(F)(F)F)ccnc1CS(=O)c1nc2ccc(O)cc2[nH]1': {0: 48, 1: 106, 2: 106, 3: 48, 4: 64, 5: 133, 6: 122, 7: 128, 8: 134, 9: 58, 10: 79, 11: 51, 12: 115, 13: 56, 14: 67, 15: 62, 16: 116, 17: 50, 18: 130, 19: 50, 20: 45, 21: 112, 22: 24, 23: 46, 24: 125, 25: 31}, 'Cc1c(OCC(F)(F)F)ccnc1CS(=O)c1nc2ccc(OC3OC(C(=O)O)C(O)C(O)C3O)cc2[nH]1': {0: 8, 1: 37, 2: 31, 3: 11, 4: 22, 5: 38, 6: 14, 7: 15, 8: 16, 9: 17, 10: 20, 11: 10, 12: 34, 13: 21, 14: 26, 15: 6, 16: 23, 17: 9, 18: 36, 19: 24, 20: 18, 21: 32, 22: 13, 23: 30, 24: 12, 25: 29, 26: 19, 27: 5, 28: 3, 29: 27, 30: 1, 31: 28, 32: 2, 33: 33, 34: 4, 35: 25, 36: 35, 37: 7}, 'Cc1c(OCC(F)(F)F)ccnc1CS(=O)c1nc2ccccc2[nH]1': {0: 49, 1: 105, 2: 105, 3: 47, 4: 63, 5: 128, 6: 118, 7: 124, 8: 130, 9: 60, 10: 81, 11: 50, 12: 111, 13: 55, 14: 65, 15: 61, 16: 113, 17: 45, 18: 121, 19: 43, 20: 42, 21: 41, 22: 45, 23: 120, 24: 28}, 'Cc1c(OCC(F)(F)F)ccnc1C[S+](O)c1nc2c(OS(=O)(=O)O)cccc2[nH]1': {0: 59, 1: 126, 2: 129, 3: 57, 4: 85, 5: 154, 6: 137, 7: 143, 8: 149, 9: 73, 10: 98, 11: 59, 12: 138, 13: 77, 14: 41, 15: 37, 16: 137, 17: 64, 18: 147, 19: 136, 20: 67, 21: 70, 22: 90, 23: 96, 24: 37, 25: 67, 26: 62, 27: 63, 28: 154, 29: 38}, 'Cc1nc(Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(CCO)CC2)n1': {0: 77, 1: 148, 2: 96, 3: 147, 4: 33, 5: 146, 6: 98, 7: 112, 8: 139, 9: 131, 10: 99, 11: 34, 12: 161, 13: 156, 14: 87, 15: 65, 16: 61, 17: 74, 18: 164, 19: 169, 20: 115, 21: 101, 22: 182, 23: 44, 24: 91, 25: 77, 26: 35, 27: 96, 28: 91, 29: 34, 30: 85, 31: 101, 32: 117}, 'Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2': {0: 6, 1: 20, 2: 1, 3: 11, 4: 19, 5: 3, 6: 15, 7: 18, 8: 10, 9: 21, 10: 7, 11: 17, 12: 16, 13: 13, 14: 23, 15: 14, 16: 9, 17: 5, 18: 12, 19: 22, 20: 8, 21: 2, 22: 4}, 'Cc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O': {0: 36, 1: 106, 2: 57, 3: 74, 4: 111, 5: 51, 6: 111, 7: 78, 8: 42, 9: 112, 10: 115, 11: 68, 12: 118, 13: 90, 14: 124, 15: 48, 16: 39, 17: 25, 18: 47, 19: 113, 20: 128, 21: 19, 22: 65, 23: 23}, 'Clc1ccc2c(c1)N=C(N1CCNCC1)c1ccccc1N2': {0: 5, 1: 22, 2: 12, 3: 16, 4: 19, 5: 20, 6: 17, 7: 3, 8: 15, 9: 4, 10: 6, 11: 8, 12: 2, 13: 9, 14: 7, 15: 21, 16: 13, 17: 10, 18: 11, 19: 14, 20: 18, 21: 1}, 'N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N(CC(=O)O)CC(=O)O)cc3)n2)cc1': {0: 62, 1: 130, 2: 80, 3: 31, 4: 133, 5: 101, 6: 152, 7: 78, 8: 89, 9: 163, 10: 159, 11: 97, 12: 111, 13: 100, 14: 183, 15: 35, 16: 169, 17: 85, 18: 65, 19: 186, 20: 44, 21: 103, 22: 138, 23: 120, 24: 45, 25: 110, 26: 145, 27: 126, 28: 51, 29: 71, 30: 96, 31: 101, 32: 110, 33: 101}, 'N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4)cc3)n2)cc1': {0: 8, 1: 24, 2: 11, 3: 3, 4: 27, 5: 7, 6: 30, 7: 12, 8: 20, 9: 31, 10: 28, 11: 23, 12: 22, 13: 2, 14: 25, 15: 1, 16: 26, 17: 14, 18: 18, 19: 29, 20: 6, 21: 16, 22: 9, 23: 5, 24: 10, 25: 17, 26: 19, 27: 15, 28: 4, 29: 21, 30: 13}, 'N#CCNC(=O)c1ccc(-c2ccnc(Nc3ccc(N4CCOCC4=O)cc3)n2)cc1': {0: 55, 1: 123, 2: 78, 3: 30, 4: 131, 5: 95, 6: 151, 7: 72, 8: 87, 9: 157, 10: 152, 11: 94, 12: 111, 13: 101, 14: 169, 15: 30, 16: 165, 17: 84, 18: 88, 19: 174, 20: 40, 21: 89, 22: 63, 23: 56, 24: 70, 25: 143, 26: 100, 27: 99, 28: 97, 29: 77, 30: 109,

In [92]:
df_total = pd.read_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_123_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrates'].to_list()
xenosite_results = [result_new[canonicalsmiles(i)] for i in substrates]
df_total['xenosite_results'] = xenosite_results
df_total

,substrates,true_sites,gnn_results,smartcyp_results,xenosite_results
0,C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)...,[3],"{0: 9, 1: 6, 2: 2, 3: 1, 4: 4, 5: 18, 6: 13, 7...","{0: 53, 1: 66, 2: 72, 3: 69, 4: 60, 5: 5, 6: 5...","{0: 65, 1: 107, 2: 138, 3: 77, 4: 107, 5: 74, ..."
1,CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cc...,"[0, 10, 19, 13]","{0: 18, 1: 5, 2: 16, 3: 3, 4: 34, 5: 36, 6: 42...","{0: 36, 1: 83, 2: 36, 3: 75, 4: 89, 5: 44, 6: ...","{0: 68, 1: 204, 2: 75, 3: 36, 4: 184, 5: 112, ..."
2,CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1,"[1, 2, 4, 5, 22, 23]","{0: 15, 1: 22, 2: 16, 3: 7, 4: 2, 5: 6, 6: 23,...","{0: 26, 1: 21, 2: 26, 3: 6, 4: 18, 5: 13, 6: 5...","{0: 46, 1: 63, 2: 53, 3: 74, 4: 30, 5: 73, 6: ..."
3,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,"[17, 10, 14]","{0: 12, 1: 6, 2: 4, 3: 5, 4: 16, 5: 13, 6: 11,...","{0: 26, 1: 11, 2: 18, 3: 30, 4: 39, 5: 24, 6: ...","{0: 56, 1: 58, 2: 64, 3: 22, 4: 108, 5: 65, 6:..."
4,CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NC...,"[2, 7, 50, 59, 60]","{0: 34, 1: 42, 2: 32, 3: 45, 4: 29, 5: 20, 6: ...","{0: 68, 1: 108, 2: 68, 3: 65, 4: 42, 5: 126, 6...","{0: 120, 1: 289, 2: 127, 3: 125, 4: 149, 5: 21..."
...,...,...,...,...,...
60,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,"[26, 47]","{0: 48, 1: 7, 2: 28, 3: 9, 4: 14, 5: 1, 6: 2, ...","{0: 64, 1: 49, 2: 64, 3: 59, 4: 30, 5: 56, 6: ...","{0: 238, 1: 229, 2: 128, 3: 268, 4: 161, 5: 28..."
61,O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1,"[0, 1, 2]","{0: 3, 1: 1, 2: 5, 3: 2, 4: 6, 5: 18, 6: 9, 7:...","{0: 30, 1: 33, 2: 3, 3: 8, 4: 48, 5: 42, 6: 19...","{0: 50, 1: 84, 2: 50, 3: 19, 4: 74, 5: 92, 6: ..."
62,O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O,"[0, 1, 19]","{0: 6, 1: 5, 2: 4, 3: 10, 4: 18, 5: 13, 6: 9, ...","{0: 30, 1: 33, 2: 27, 3: 42, 4: 20, 5: 11, 6: ...","{0: 55, 1: 90, 2: 20, 3: 103, 4: 60, 5: 39, 6:..."
63,O=P1(NCCCl)OCCCN1CCCl,"[2, 9, 10, 11]","{0: 6, 1: 8, 2: 1, 3: 2, 4: 11, 5: 12, 6: 13, ...","{0: 30, 1: 33, 2: 15, 3: 6, 4: 24, 6: 30, 7: 1...","{0: 54, 1: 39, 2: 23, 3: 46, 4: 41, 5: 70, 6: ..."
64,OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1,[1],"{0: 1, 1: 2, 2: 17, 3: 11, 4: 6, 5: 24, 6: 10,...","{0: 45, 1: 13, 2: 16, 3: 51, 4: 28, 5: 7, 6: 2...","{0: 27, 1: 65, 2: 59, 3: 70, 4: 71, 5: 93, 6: ..."

In [93]:
df_total.to_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_65_site_truth_correct_withatomidx_noenzyme.pickle')