In [1]:
import json
import os
import pandas as pd

dirpath1 = '/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/xenosite/30_main_cases'
pathlist1 = os.listdir(dirpath1)
pathlist1 = [dirpath1+'/'+i for i in pathlist1 if i.endswith('.txt')]

# dirpath2 = '/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/xenosite/add_unnamed_files'
# pathlist2 = os.listdir(dirpath2)
# pathlist2 = [dirpath2+'/'+i for i in pathlist2 if i.endswith('.txt')]

pathlist = pathlist1# + pathlist2

smiles_new = []
models_new = []
atomscores_new = []
bondscores_new = []

# pathlist = ['unnamed (1).txt']

for path in pathlist:

    try:
        # 读取文件内容
        with open(path, 'r') as file:
            data = json.load(file)

        # 提取 SMILES
        smiles = data.get('smiles')

        # 提取每个 model 的信息
        models_info = []

        for result in data['results']:
            model = result.get('model')
            atom = result.get('atom')
            bonds = result.get('bond')

            # 保存每个 model 的详细信息
            smiles_new.append(smiles)
            models_new.append(model)
            atomscores_new.append(atom)
            bondscores_new.append(bonds)
    except:
        print(path)
    

# 打印结果

# print("SMILES:", smiles)
# for model_info in models_info:
#     print("\nModel:", model_info['model'])
#     print("Atoms:", model_info['atom'])
#     print("Bonds:", model_info['bond'])

df_new = pd.DataFrame()
df_new['substrates'] = smiles_new
df_new['enzyme'] = models_new
df_new['atomscores'] = atomscores_new
df_new['bondscores'] = bondscores_new
df_new

/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/xenosite/30_main_cases/unnamed.txt
/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/xenosite/30_main_cases/unnamed (20).txt
/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/xenosite/30_main_cases/unnamed (54).txt

,substrates,enzyme,atomscores,bondscores
0,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.stable_oxygenation,"[0.04688301682472229, 5.322694778442383e-05, 0...","[5.91278076171875e-05, 0.0018117129802703857, ..."
1,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.unstable_oxygenation,"[1.5467405319213867e-05, 2.682209014892578e-07...","[0.006465315818786621, 0.007032662630081177, 0..."
2,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.dehydrogenation,"[0.0017002522945404053, 8.940696716308594e-08,...","[5.960464477539063e-08, 8.58306884765625e-06, ..."
3,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.hydrolysis,"[2.8908252716064453e-06, 2.2351741790771484e-0...","[6.285309791564941e-05, 0.002713918685913086, ..."
4,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.reduction,"[0, 0, 0, 0, 0, 0, 3.5762786865234375e-07, 3.5...","[0, 5.364418029785156e-07, 1.823902130126953e-..."
...,...,...,...,...
130,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.stable_oxygenation,"[0.032869696617126465, 0.04651036858558655, 0....","[4.088878631591797e-05, 5.111098289489746e-05,..."
131,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.unstable_oxygenation,"[1.576542854309082e-05, 1.4960765838623047e-05...","[0.005626857280731201, 0.005427330732345581, 0..."
132,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.dehydrogenation,"[0.001680523157119751, 0.0021561086177825928, ...","[6.258487701416016e-07, 5.066394805908203e-07,..."
133,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.hydrolysis,"[3.844499588012695e-06, 3.1888484954833984e-06...","[1.5050172805786133e-05, 8.52048397064209e-05,..."
134,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.reduction,"[0, 0, 0, 0, 0, 0, 1.2367963790893555e-05, 0, ...","[0, 2.9802322387695312e-08, 2.9802322387695312..."

In [2]:
df_new.drop_duplicates(subset=['substrates','enzyme'],keep='first',inplace=True,ignore_index=True)

In [3]:
df_new

,substrates,enzyme,atomscores,bondscores
0,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.stable_oxygenation,"[0.04688301682472229, 5.322694778442383e-05, 0...","[5.91278076171875e-05, 0.0018117129802703857, ..."
1,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.unstable_oxygenation,"[1.5467405319213867e-05, 2.682209014892578e-07...","[0.006465315818786621, 0.007032662630081177, 0..."
2,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.dehydrogenation,"[0.0017002522945404053, 8.940696716308594e-08,...","[5.960464477539063e-08, 8.58306884765625e-06, ..."
3,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.hydrolysis,"[2.8908252716064453e-06, 2.2351741790771484e-0...","[6.285309791564941e-05, 0.002713918685913086, ..."
4,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.reduction,"[0, 0, 0, 0, 0, 0, 3.5762786865234375e-07, 3.5...","[0, 5.364418029785156e-07, 1.823902130126953e-..."
...,...,...,...,...
123,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.stable_oxygenation,"[0.032869696617126465, 0.04651036858558655, 0....","[4.088878631591797e-05, 5.111098289489746e-05,..."
124,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.unstable_oxygenation,"[1.576542854309082e-05, 1.4960765838623047e-05...","[0.005626857280731201, 0.005427330732345581, 0..."
125,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.dehydrogenation,"[0.001680523157119751, 0.0021561086177825928, ...","[6.258487701416016e-07, 5.066394805908203e-07,..."
126,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.hydrolysis,"[3.844499588012695e-06, 3.1888484954833984e-06...","[1.5050172805786133e-05, 8.52048397064209e-05,..."
127,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.reduction,"[0, 0, 0, 0, 0, 0, 1.2367963790893555e-05, 0, ...","[0, 2.9802322387695312e-08, 2.9802322387695312..."

In [4]:
from collections import Counter


# 假设你有一个列表
example_list = df_new['substrates'].to_list()

# 使用 Counter 计数
element_count = Counter(example_list)

# 输出结果
for key, count in element_count.items():
    if count < 6:
        print(key)

Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1
O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O
CC(C)(C)C(NC(=O)C(F)(F)F)C(=O)N1CC2(CC1C(=O)NC(C#N)CC1CCNC1=O)SCCS2
COc1c(C2C(C(=O)Nc3ccnc(C(N)=O)c3)OC(C)(C(F)(F)F)C2C)ccc(F)c1F
Cn1cnc2ncn(Cc3nc(C4COC(c5ccc(Cl)cc5)C4)no3)c(=O)c21
CN(C(=O)Cc1cccs1)C(Cc1c[nH]c2ccccc12)C(=O)NC(C)(Cc1ccccc1)C(=O)NC(CCCNC(=N)N)C(=O)N1CCCC1C(=O)NC(CCCNC(=N)N)C(N)=O
CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1
CN1CCCC(OC(=O)C(O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNCC(O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1
CNC(C)Cc1ccc2c(c1)OCO2
O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1

In [5]:
from rdkit import Chem
def canonicalsmiles(smiles):
    mol = Chem.MolFromSmiles(smiles)
    smi_new = Chem.MolToSmiles(mol, isomericSmiles=False)
    return smi_new

In [6]:
# 输出的结果会失去立体构象
smiles_now = list(set(df_new['substrates'].to_list()))
smiles_now = list(map(canonicalsmiles,smiles_now))

df = pd.read_csv('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/main_cases/pred_results_score_new.csv')
smiles_shouldbe = df['substrate'].to_list()
smiles_shouldbe = list(map(canonicalsmiles,smiles_shouldbe))

smiles_out = [i for i in smiles_shouldbe if i not in smiles_now]
for i in smiles_out:
    print(i)

CC1OC(OC2C(OC(=O)C34CCC(C)(C)CC3C3=CCC5C6(C)CC(O)C(OC7OC(CO)C(O)C(O)C7O)C(CO)(CO)C6CCC5(C)C3(C)CC4O)OCC(O)C2O)C(O)C(O)C1OC1OCC(O)C(OC2OCC(O)C2(O)CO)C1O

In [7]:
df_new.to_pickle('xenosite_results_30.pickle')

In [8]:
df =  pd.read_pickle('xenosite_results_30.pickle')
df

,substrates,enzyme,atomscores,bondscores
0,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.stable_oxygenation,"[0.04688301682472229, 5.322694778442383e-05, 0...","[5.91278076171875e-05, 0.0018117129802703857, ..."
1,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.unstable_oxygenation,"[1.5467405319213867e-05, 2.682209014892578e-07...","[0.006465315818786621, 0.007032662630081177, 0..."
2,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.dehydrogenation,"[0.0017002522945404053, 8.940696716308594e-08,...","[5.960464477539063e-08, 8.58306884765625e-06, ..."
3,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.hydrolysis,"[2.8908252716064453e-06, 2.2351741790771484e-0...","[6.285309791564941e-05, 0.002713918685913086, ..."
4,Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1,phase1.reduction,"[0, 0, 0, 0, 0, 0, 3.5762786865234375e-07, 3.5...","[0, 5.364418029785156e-07, 1.823902130126953e-..."
...,...,...,...,...
123,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.stable_oxygenation,"[0.032869696617126465, 0.04651036858558655, 0....","[4.088878631591797e-05, 5.111098289489746e-05,..."
124,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.unstable_oxygenation,"[1.576542854309082e-05, 1.4960765838623047e-05...","[0.005626857280731201, 0.005427330732345581, 0..."
125,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.dehydrogenation,"[0.001680523157119751, 0.0021561086177825928, ...","[6.258487701416016e-07, 5.066394805908203e-07,..."
126,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.hydrolysis,"[3.844499588012695e-06, 3.1888484954833984e-06...","[1.5050172805786133e-05, 8.52048397064209e-05,..."
127,CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N...,phase1.reduction,"[0, 0, 0, 0, 0, 0, 1.2367963790893555e-05, 0, ...","[0, 2.9802322387695312e-08, 2.9802322387695312..."

In [9]:
df =  pd.read_pickle('xenosite_results_30.pickle')
atomscores = df['atomscores'].to_list()

# 使用字典推导式生成字典
atomscores = [{idx: score for idx, score in enumerate(i)} for i in atomscores]
df['atomscores'] = atomscores

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result
def assign_ranks(atom_scores):
    # 按分数降序排序，并获取排序后的原子序号
    sorted_atoms = sorted(atom_scores.items(), key=lambda x: x[1], reverse=True)
    
    # 创建一个字典，保存原子序号对应的排名
    rank_dict = {}
    for rank, (atom, _) in enumerate(sorted_atoms):
        rank_dict[atom] = rank + 1
    
    # 保持原子序号从小到大的顺序，并更新为对应的排名
    ranked_atoms = {atom: rank_dict[atom] for atom in sorted(atom_scores)}
    
    return ranked_atoms

atomscores = df['atomscores'].to_list()
atomscores = list(map(assign_ranks,atomscores))
df['atomscores'] = atomscores
# df.to_pickle('xenosite_results_withrank.pickle')
# 示例
result = group_by_column_to_dict(df, 'substrates', 'atomscores')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'C=CC(=O)Nc1cc(Nc2ncc(C(=O)OC(C)C)c(-c3cn(C)c4ccccc34)n2)c(OC)cc1N(C)CCN(C)C': {0: 52, 1: 73, 2: 167, 3: 118, 4: 37, 5: 198, 6: 137, 7: 188, 8: 34, 9: 207, 10: 130, 11: 156, 12: 221, 13: 148, 14: 139, 15: 122, 16: 104, 17: 87, 18: 93, 19: 207, 20: 210, 21: 150, 22: 83, 23: 113, 24: 220, 25: 93, 26: 83, 27: 114, 28: 102, 29: 212, 30: 155, 31: 231, 32: 96, 33: 122, 34: 155, 35: 243, 36: 37, 37: 136, 38: 128, 39: 105, 40: 40, 41: 112, 42: 118}, 'CC(=O)Nc1ccc(C)c(C(=O)NC(C)c2cccc3ccccc23)c1': {0: 59, 1: 103, 2: 71, 3: 23, 4: 138, 5: 61, 6: 72, 7: 123, 8: 66, 9: 140, 10: 112, 11: 73, 12: 24, 13: 79, 14: 64, 15: 131, 16: 84, 17: 78, 18: 42, 19: 137, 20: 43, 21: 50, 22: 57, 23: 69, 24: 139, 25: 68}, 'CC(C)(C)C(NC(=O)C(F)(F)F)C(=O)N1CC2(CC1C(=O)NC(C#N)CC1CCNC1=O)SCCS2': {0: 13, 1: 36, 2: 14, 3: 15, 4: 29, 5: 3, 6: 31, 7: 2, 8: 35, 9: 17, 10: 18, 11: 19, 12: 33, 13: 10, 14: 11, 15: 12, 16: 23, 17: 7, 18: 26, 19: 32, 20: 6, 21: 5, 22: 28, 23: 34, 24: 16, 25: 22, 26: 27, 27: 21, 28: 20, 29: 1, 30: 30, 31: 4, 32: 8, 33: 24, 34: 25, 35: 9}, 'CC=CC#CC#CC(O)C(C=CCCCO)OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O': {0: 112, 1: 94, 2: 98, 3: 186, 4: 189, 5: 205, 6: 182, 7: 129, 8: 63, 9: 152, 10: 108, 11: 97, 12: 143, 13: 114, 14: 91, 15: 32, 16: 127, 17: 140, 18: 167, 19: 148, 20: 144, 21: 145, 22: 119, 23: 157, 24: 131, 25: 128, 26: 46, 27: 117, 28: 64, 29: 133, 30: 71, 31: 114, 32: 91, 33: 130, 34: 77, 35: 148, 36: 74, 37: 122, 38: 92}, 'CCC(C(=O)Nc1ccc(C(N)=O)c(F)c1)n1cc(OC)c(-c2cc(Cl)ccc2-n2cc(C(F)(F)F)nn2)cc1=O': {0: 50, 1: 54, 2: 76, 3: 123, 4: 94, 5: 22, 6: 170, 7: 75, 8: 67, 9: 159, 10: 129, 11: 24, 12: 90, 13: 152, 14: 175, 15: 93, 16: 51, 17: 118, 18: 176, 19: 67, 20: 82, 21: 165, 22: 178, 23: 106, 24: 171, 25: 190, 26: 87, 27: 102, 28: 192, 29: 100, 30: 111, 31: 195, 32: 216, 33: 203, 34: 209, 35: 215, 36: 120, 37: 132, 38: 126, 39: 211, 40: 90}, 'CCC(C)C(=O)N1CCC(NC(=O)Nc2ccc(OC(F)(F)F)c(F)c2)CC1': {0: 57, 1: 58, 2: 64, 3: 56, 4: 100, 5: 74, 6: 38, 7: 61, 8: 51, 9: 65, 10: 30, 11: 113, 12: 76, 13: 27, 14: 129, 15: 81, 16: 67, 17: 130, 18: 72, 19: 144, 20: 132, 21: 138, 22: 144, 23: 127, 24: 154, 25: 98, 26: 69, 27: 81}, 'CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3c(N)ncnn23)C(O)C1O)Oc1ccccc1': {0: 66, 1: 78, 2: 97, 3: 85, 4: 75, 5: 113, 6: 129, 7: 166, 8: 126, 9: 143, 10: 111, 11: 61, 12: 120, 13: 177, 14: 134, 15: 101, 16: 127, 17: 102, 18: 225, 19: 181, 20: 109, 21: 210, 22: 151, 23: 125, 24: 224, 25: 208, 26: 31, 27: 129, 28: 161, 29: 159, 30: 165, 31: 116, 32: 49, 33: 130, 34: 47, 35: 139, 36: 217, 37: 132, 38: 120, 39: 111, 40: 127, 41: 141}, 'CCCCCc1cc(O)c2c(c1)OC(C)(C)C1CCC(C)CC21': {0: 31, 1: 34, 2: 47, 3: 49, 4: 60, 5: 109, 6: 70, 7: 115, 8: 34, 9: 114, 10: 121, 11: 80, 12: 57, 13: 130, 14: 66, 15: 72, 16: 70, 17: 72, 18: 58, 19: 50, 20: 57, 21: 72, 22: 88}, 'CCN(CC)C(=O)C1C=C2c3cccc4c3c(cn4C(=O)C3CC3)CC2N(C)C1': {0: 48, 1: 66, 2: 36, 3: 72, 4: 56, 5: 125, 6: 91, 7: 93, 8: 66, 9: 122, 10: 140, 11: 100, 12: 76, 13: 77, 14: 155, 15: 147, 16: 150, 17: 115, 18: 63, 19: 121, 20: 81, 21: 94, 22: 57, 23: 63, 24: 87, 25: 92, 26: 40, 27: 95, 28: 82}, 'CCN(CC)CCc1c[nH]c2cccc(OC(C)=O)c12': {0: 38, 1: 42, 2: 17, 3: 48, 4: 46, 5: 57, 6: 56, 7: 95, 8: 80, 9: 28, 10: 109, 11: 46, 12: 44, 13: 58, 14: 108, 15: 55, 16: 85, 17: 73, 18: 60, 19: 115}, 'CCOc1ccc(NC(=S)N(CCO)Cc2cc3cc(C)cc(C)c3[nH]c2=O)cc1': {0: 17, 1: 8, 2: 7, 3: 23, 4: 14, 5: 19, 6: 28, 7: 3, 8: 22, 9: 5, 10: 16, 11: 11, 12: 10, 13: 1, 14: 6, 15: 30, 16: 21, 17: 27, 18: 18, 19: 26, 20: 13, 21: 12, 22: 29, 23: 9, 24: 24, 25: 2, 26: 25, 27: 4, 28: 20, 29: 15}, 'CN(C(=O)Cc1cccs1)C(Cc1c[nH]c2ccccc12)C(=O)NC(C)(Cc1ccccc1)C(=O)NC(CCCNC(=N)N)C(=O)N1CCCC1C(=O)NC(CCCNC(=N)N)C(N)=O': {0: 33, 1: 36, 2: 53, 3: 14, 4: 43, 5: 63, 6: 51, 7: 49, 8: 45, 9: 32, 10: 47, 11: 29, 12: 65, 13: 52, 14: 7, 15: 61, 16: 42, 17: 13, 18: 21, 19: 40, 20: 64, 21: 54, 22: 11, 23: 15, 24: 57, 25: 26, 26: 30, 27: 62, 28: 38, 29: 22, 30: 24, 31: 23, 32: 39, 33: 60, 34: 18, 35: 17, 36: 46, 37: 25, 38: 34, 39: 31, 40: 8, 41: 59, 42: 4, 43: 2, 44: 58, 45: 16, 46: 28, 47: 19, 48: 27, 49: 20, 50: 48, 51: 56, 52: 12, 53: 10, 54: 44, 55: 35, 56: 41, 57: 37, 58: 6, 59: 50, 60: 3, 61: 1, 62: 55, 63: 5, 64: 9}, 'CN1CCCC(OC(=O)C(O)(c2ccccc2)c2cccc(OCCCNC(=O)c3ccc(CNCC(O)c4ccc(O)c5[nH]c(=O)ccc45)cc3)c2)C1': {0: 17, 1: 9, 2: 13, 3: 11, 4: 24, 5: 27, 6: 23, 7: 42, 8: 18, 9: 47, 10: 2, 11: 51, 12: 29, 13: 21, 14: 19, 15: 22, 16: 30, 17: 50, 18: 37, 19: 32, 20: 35, 21: 49, 22: 14, 23: 15, 24: 25, 25: 10, 26: 8, 27: 43, 28: 7, 29: 54, 30: 40, 31: 38, 32: 53, 33: 12, 34: 5, 35: 20, 36: 33, 37: 3, 38: 52, 39: 34, 40: 26, 41: 45, 42: 1, 43: 46, 44: 4, 45: 36, 46: 6, 47: 28, 48: 31, 49: 48, 50: 39, 51: 41, 52: 44, 53: 16}, 'CNC(C)Cc1ccc2c(c1)OCO2': {0: 6, 1: 1, 2: 9, 3: 7, 4: 5, 5: 12, 6: 10, 7: 8, 8: 13, 9: 14, 10: 11, 11: 4, 12: 2, 13: 3}, 'COc1c(C2C(C(=O)Nc3ccnc(C(N)=O)c3)OC(C)(C(F)(F)F)C2C)ccc(F)c1F': {0: 7, 1: 9, 2: 30, 3: 32, 4: 13, 5: 14, 6: 24, 7: 6, 8: 3, 9: 27, 10: 20, 11: 15, 12: 1, 13: 28, 14: 25, 15: 2, 16: 4, 17: 23, 18: 5, 19: 26, 20: 10, 21: 33, 22: 16, 23: 17, 24: 18, 25: 21, 26: 8, 27: 22, 28: 19, 29: 29, 30: 11, 31: 31, 32: 12}, 'COc1ccc(CCCCOC2OC(CO)C(O)C(O)C2O)cc1': {0: 90, 1: 61, 2: 132, 3: 71, 4: 90, 5: 131, 6: 77, 7: 79, 8: 77, 9: 85, 10: 78, 11: 70, 12: 89, 13: 68, 14: 79, 15: 25, 16: 63, 17: 35, 18: 75, 19: 38, 20: 64, 21: 49, 22: 96, 23: 78}, 'COc1ccc2c(Oc3ccc(C4(C(=O)NO)CCOCC4)cc3)ccnc2n1': {0: 52, 1: 65, 2: 136, 3: 71, 4: 68, 5: 144, 6: 133, 7: 67, 8: 130, 9: 65, 10: 88, 11: 138, 12: 160, 13: 115, 14: 87, 15: 29, 16: 49, 17: 65, 18: 57, 19: 47, 20: 63, 21: 73, 22: 101, 23: 71, 24: 92, 25: 108, 26: 97, 27: 161, 28: 78}, 'Cc1ccc(C2OC(CO)C(O)C(O)C2O)cc1Cc1ccc(-c2ccc(F)cc2)s1': {0: 82, 1: 143, 2: 83, 3: 103, 4: 156, 5: 84, 6: 94, 7: 71, 8: 74, 9: 32, 10: 56, 11: 42, 12: 69, 13: 41, 14: 69, 15: 49, 16: 114, 17: 154, 18: 71, 19: 145, 20: 118, 21: 111, 22: 154, 23: 159, 24: 62, 25: 70, 26: 155, 27: 164, 28: 76, 29: 68, 30: 107}, 'Cc1ccc(N)cc1C(=O)NC(C)c1cccc2ccccc12': {0: 55, 1: 104, 2: 63, 3: 30, 4: 116, 5: 12, 6: 54, 7: 118, 8: 109, 9: 63, 10: 26, 11: 64, 12: 57, 13: 117, 14: 76, 15: 86, 16: 42, 17: 122, 18: 48, 19: 45, 20: 54, 21: 66, 22: 129}, 'Cc1ncc(S(=O)(=O)N2CCC(c3cn4ncnc4cc3Cl)CC2)s1': {0: 33, 1: 84, 2: 52, 3: 63, 4: 63, 5: 37, 6: 65, 7: 70, 8: 27, 9: 47, 10: 41, 11: 46, 12: 95, 13: 62, 14: 71, 15: 56, 16: 70, 17: 49, 18: 110, 19: 54, 20: 104, 21: 122, 22: 57, 23: 65, 24: 82}, 'Cn1cc(Nc2nccc(N3CC4CCC(C3)N4C(=O)C3CC3(F)F)n2)cn1': {0: 62, 1: 46, 2: 72, 3: 128, 4: 29, 5: 133, 6: 81, 7: 85, 8: 85, 9: 133, 10: 34, 11: 75, 12: 81, 13: 55, 14: 61, 15: 89, 16: 85, 17: 43, 18: 121, 19: 78, 20: 86, 21: 59, 22: 153, 23: 146, 24: 152, 25: 102, 26: 103, 27: 59}, 'Cn1cnc2ncn(Cc3nc(C4COC(c5ccc(Cl)cc5)C4)no3)c(=O)c21': {0: 13, 1: 6, 2: 20, 3: 2, 4: 24, 5: 1, 6: 22, 7: 11, 8: 12, 9: 25, 10: 3, 11: 19, 12: 23, 13: 7, 14: 10, 15: 21, 16: 28, 17: 17, 18: 15, 19: 26, 20: 14, 21: 16, 22: 18, 23: 9, 24: 4, 25: 8, 26: 27, 27: 5, 28: 29}, 'N#CC1CN(S(=O)(=O)c2cccc(C(=O)N3CCCC3C(=O)NCc3ccc(C(F)(F)F)cc3)c2)C1': {0: 60, 1: 128, 2: 96, 3: 85, 4: 51, 5: 80, 6: 119, 7: 125, 8: 155, 9: 97, 10: 98, 11: 96, 12: 172, 13: 151, 14: 108, 15: 27, 16: 88, 17: 66, 18: 60, 19: 106, 20: 147, 21: 94, 22: 33, 23: 111, 24: 169, 25: 70, 26: 88, 27: 169, 28: 199, 29: 181, 30: 187, 31: 193, 32: 99, 33: 76, 34: 101, 35: 111}, 'NC1(C(=O)NC(CCO)c2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1': {0: 44, 1: 148, 2: 119, 3: 87, 4: 45, 5: 94, 6: 73, 7: 55, 8: 30, 9: 143, 10: 65, 11: 65, 12: 135, 13: 151, 14: 71, 15: 71, 16: 71, 17: 89, 18: 48, 19: 157, 20: 105, 21: 115, 22: 84, 23: 158, 24: 44, 25: 95, 26: 72, 27: 168, 28: 102, 29: 86}, 'O=C(CCC(F)(F)F)N1CCC2(CC1)CC(C(F)(F)F)=NO2': {0: 44, 1: 65, 2: 46, 3: 40, 4: 85, 5: 77, 6: 83, 7: 89, 8: 23, 9: 44, 10: 41, 11: 103, 12: 48, 13: 53, 14: 52, 15: 78, 16: 117, 17: 113, 18: 119, 19: 125, 20: 26, 21: 47}, 'O=C(Nc1ccc(OC(F)(F)F)cc1)c1sccc1NCc1ccnc2ccccc12': {0: 80, 1: 102, 2: 27, 3: 140, 4: 77, 5: 51, 6: 141, 7: 71, 8: 152, 9: 139, 10: 145, 11: 151, 12: 57, 13: 88, 14: 122, 15: 56, 16: 87, 17: 93, 18: 150, 19: 23, 20: 82, 21: 140, 22: 77, 23: 107, 24: 45, 25: 162, 26: 63, 27: 46, 28: 84, 29: 69, 30: 149}, 'O=C(O)C1OC(Oc2cc3oc(-c4ccc(O)cc4)cc(=O)c3c(O)c2O)C(O)C(O)C1O': {0: 9, 1: 15, 2: 3, 3: 30, 4: 14, 5: 31, 6: 11, 7: 27, 8: 21, 9: 22, 10: 10, 11: 29, 12: 32, 13: 18, 14: 12, 15: 16, 16: 1, 17: 13, 18: 19, 19: 17, 20: 25, 21: 8, 22: 23, 23: 24, 24: 4, 25: 20, 26: 2, 27: 33, 28: 7, 29: 28, 30: 6, 31: 26, 32: 5}, 'O=C(c1cccnc1-c1ccncc1)N1CCC(O)(Cc2ccccc2)CC1': {0: 7, 1: 24, 2: 28, 3: 22, 4: 21, 5: 17, 6: 3, 7: 26, 8: 27, 9: 18, 10: 11, 11: 2, 12: 12, 13: 19, 14: 6, 15: 4, 16: 13, 17: 23, 18: 1, 19: 20, 20: 25, 21: 15, 22: 9, 23: 8, 24: 10, 25: 16, 26: 14, 27: 5}, 'O=C1CCC(N2Cc3c(OCc4ccc(CN5CCOCC5)cc4)cccc3C2=O)C(=O)N1': {0: 91, 1: 137, 2: 79, 3: 59, 4: 110, 5: 43, 6: 90, 7: 163, 8: 175, 9: 68, 10: 92, 11: 157, 12: 87, 13: 95, 14: 166, 15: 100, 16: 30, 17: 79, 18: 61, 19: 64, 20: 67, 21: 87, 22: 107, 23: 93, 24: 99, 25: 123, 26: 93, 27: 184, 28: 168, 29: 106, 30: 163, 31: 95, 32: 35}}

In [14]:
df_total = pd.read_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_30_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrate'].to_list()
xenosite_results = [result_new[canonicalsmiles(i)] for i in substrates]
df_total['xenosite_results'] = xenosite_results
df_total

,substrate,predict,metabolite,site_truth,pred_site,sites,gnn_results,somp_results,xenosite_results
0,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)O,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\C(=O)...,CC(/C=C/[C@]12O[C@]1(C)CCCC2(C)C)=C\C=C\C(C)=C...,CC(/C=C/C12C(C)(C)CCC[C:1]1(C)[O:1]2)=C\C=C\C(...,CC(/C=C/C12OC1(C)CCCC2(C)C)=C\C=C\C(C)=C\[C:1]...,"[20, 22]","{0: 23, 1: 20, 2: 21, 3: 16, 4: 11, 5: 17, 6: ...","{0: 65, 1: 85, 2: 81, 3: 60, 4: 58, 5: 63, 6: ...","{0: 49, 1: 91, 2: 68, 3: 67, 4: 115, 5: 48, 6:..."
1,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2,NC1=CC=C2C(=C1)C(C1=CC=CC=C1Cl)=NCC(=O)N2|CC(=...,CC(=O)Nc1ccc2c(c1)C(c1ccccc1Cl)=NC(O)C(=O)N2,CC(=O)Nc1cc2c([cH:1]c1)NC(=O)CN=C2c1ccccc1Cl|C...,CC(=O)[NH:1]c1ccc2c(c1)C(c1ccccc1Cl)=NCC(=O)N2...,[19],"{0: 13, 1: 3, 2: 17, 3: 6, 4: 14, 5: 11, 6: 20...","{0: 42, 1: 65, 2: 79, 3: 46, 4: 109, 5: 30, 6:...","{0: 42, 1: 63, 2: 57, 3: 15, 4: 95, 5: 38, 6: ..."
2,CC(=O)Nc1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc4ccc(...,CC1=C2C(=C(NC3=CC=C(I)C=C3F)N(C)C1=O)C(=O)N(C1...,Cc1c(=O)n(C)c(Nc2ccc(I)cc2F)c2c(=O)n(C3CC3)c(=...,CC(=O)N[c:1]1[cH:1][cH:1][cH:1][c:1](-n2c(=O)n...,CC(=O)[NH:1]c1cccc(-n2c(=O)n(C3CC3)c(=O)c3c(Nc...,"[3, 2, 3, 36]","{0: 11, 1: 4, 2: 19, 3: 3, 4: 20, 5: 18, 6: 17...","{0: 74, 1: 145, 2: 171, 3: 89, 4: 215, 5: 47, ...","{0: 71, 1: 119, 2: 88, 3: 19, 4: 157, 5: 76, 6..."
3,CC(C)(C)c1cc(C(C)(C)C)c(NC(=O)c2c[nH]c3ccccc3c...,CC(C)(C)C1=CC(C(C)(C)CO)=C(O)C=C1NC(=O)C1=CNC2...,CC(C)(C)c1cc(C(C)(C)C(=O)O)c(O)cc1NC(=O)c1c[nH...,CC(C)(C)c1c(NC(=O)c2c[nH]c3ccccc3c2=O)cc([OH:1...,CC(C)(C)c1cc(C(C)(C)[CH3:1])c(O)cc1NC(=O)c1c[n...,[10],"{0: 8, 1: 14, 2: 16, 3: 11, 4: 6, 5: 15, 6: 19...","{0: 30, 1: 72, 2: 36, 3: 42, 4: 113, 5: 91, 6:...","{0: 47, 1: 145, 2: 54, 3: 60, 4: 133, 5: 87, 6..."
4,CC(C)(C)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCC...,CC(C)(CO)C1=CC(NC(=O)NC2=CC=C(C3=CN4C(=N3)SC3=...,CC(C)(CO)c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OC...,CC(C)(C)[c:1]1[cH:1][c:1](NC(=O)Nc2ccc(-c3cn4c...,CC(C)(c1cc(NC(=O)Nc2ccc(-c3cn4c(n3)sc3cc(OCCN5...,[39],"{0: 12, 1: 8, 2: 11, 3: 7, 4: 28, 5: 29, 6: 40...","{0: 57, 1: 52, 2: 63, 3: 69, 4: 144, 5: 89, 6:...","{0: 12, 1: 40, 2: 13, 3: 14, 4: 37, 5: 36, 6: ..."
...,...,...,...,...,...,...,...,...,...
118,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CCOCc3ccccc3)(...,OCC[N+]12CCC(C(O)(C3=CC=CC=C3)C3=CC=CC=C3)(CC1...,OCC[N+]12CCC(C(O)(c3ccccc3)c3ccccc3)(CC1)CC2|O...,OC(c1ccccc1)(C12CC[N+](CCOCc3ccccc3)(CC1)CC2)[...,OC(c1ccccc1)(c1ccccc1)C12CC[N+](CC[O:1]Cc3cccc...,"[25, 20]","{0: 2, 1: 1, 2: 27, 3: 20, 4: 25, 5: 32, 6: 23...",None,"{0: 1, 1: 28, 2: 31, 3: 19, 4: 3, 5: 12, 6: 4,..."
119,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc(OCCOC4CC4)cc...,OC[C@H]1O[C@@H](C2=CC=C(Cl)C(CC3=CC=C(O)C=C3)=...,O=C(O)[C@H]1OC(O[C@@H]2[C@@H](O)[C@H](c3ccc(Cl...,OC[C@H]1O[C@@H]([c:1]2ccc(Cl)c(Cc3ccc(OCCOC4CC...,OC[C@H]1O[C@@H](c2ccc(Cl)c(Cc3ccc([O:1]CCOC4CC...,"[28, 29, 19, 18, 19, 11]","{0: 2, 1: 6, 2: 26, 3: 32, 4: 21, 5: 17, 6: 12...","{0: 149, 1: 31, 2: 140, 3: 62, 4: 160, 5: 157,...","{0: 35, 1: 76, 2: 81, 3: 104, 4: 99, 5: 162, 6..."
120,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2,O=CC1=CN=C(CO)N1C1=CC=C(Cl)C=C1C(=O)C1=CC=CC=C...,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=NC2O|O=C(O...,Fc1ccccc1C1=NCc2cn[c:1](C[OH:1])n2-c2ccc(Cl)cc...,OCc1ncc2n1-c1ccc(Cl)cc1C(c1ccccc1F)=N[CH2:1]2|...,"[15, 6, 23]","{0: 2, 1: 1, 2: 3, 3: 8, 4: 21, 5: 10, 6: 5, 7...","{0: 61, 1: 13, 2: 82, 3: 46, 4: 64, 5: 99, 6: ...","{0: 19, 1: 40, 2: 107, 3: 52, 4: 72, 5: 113, 6..."
121,Oc1ccc(COCC[N+]23CCC(C(O)(c4ccccc4)c4ccccc4)(C...,OCC[N+]12CCC(C(O)(C3=CC=CC=C3)C3=CC=CC=C3)(CC1...,O=C(O)C1OC(Oc2ccc(COCC[N+]34CCC(C(O)(c5ccccc5)...,OC(c1ccccc1)(c1c[cH:1][cH:1][cH:1][cH:1]1)C12C...,Oc1ccc(C[O:1]CC[N+]23CCC(C(O)(c4ccccc4)c4ccccc...,[26],"{0: 3, 1: 5, 2: 13, 3: 32, 4: 33, 5: 7, 6: 4, ...",None,"{0: 36, 1: 167, 2: 70, 3: 95, 4: 160, 5: 87, 6..."
122,c1cnc(N2CCNCC2)nc1,OC1=CN=C(N2CCNCC2)N=C1|OC1CN(C2=NC=CC=N2)CCN1|...,Oc1cnc(N2CCNCC2)nc1,C1CN([c:1]2[n:1][cH:1][cH:1][cH:1][n:1]2)CCN1|...,c1nc(N2CCNCC2)nc[cH:1]1|c1cnc(N2CCN[CH2:1]C2)n...,[11],"{0: 10, 1: 12, 2: 6, 3: 8, 4: 1, 5: 2, 6: 3, 7...","{0: 13, 1: 48, 2: 43, 3: 58, 4: 52, 5: 25, 6: ...","{0: 36, 1: 38, 2: 41, 3: 67, 4: 24, 5: 39, 6: ..."

In [15]:
df_total.to_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_123_site_truth_correct_withatomidx_noenzyme.pickle')