In [73]:
import json
import os
import pandas as pd

dirpath1 = '/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/xenosite'
pathlist1 = os.listdir(dirpath1)
pathlist1 = [dirpath1+'/'+i for i in pathlist1 if i.endswith('.txt')]

dirpath2 = '/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/xenosite/add_unnamed_files'
pathlist2 = os.listdir(dirpath2)
pathlist2 = [dirpath2+'/'+i for i in pathlist2 if i.endswith('.txt')]

pathlist = pathlist1 + pathlist2

smiles_new = []
models_new = []
atomscores_new = []
bondscores_new = []

# pathlist = ['unnamed (1).txt']

for path in pathlist:

    try:
        # 读取文件内容
        with open(path, 'r') as file:
            data = json.load(file)

        # 提取 SMILES
        smiles = data.get('smiles')

        # 提取每个 model 的信息
        models_info = []

        for result in data['results']:
            model = result.get('model')
            atom = result.get('atom')
            bonds = result.get('bond')

            # 保存每个 model 的详细信息
            smiles_new.append(smiles)
            models_new.append(model)
            atomscores_new.append(atom)
            bondscores_new.append(bonds)
    except:
        print(path)
    

# 打印结果

# print("SMILES:", smiles)
# for model_info in models_info:
#     print("\nModel:", model_info['model'])
#     print("Atoms:", model_info['atom'])
#     print("Bonds:", model_info['bond'])

df_new = pd.DataFrame()
df_new['substrates'] = smiles_new
df_new['enzyme'] = models_new
df_new['atomscores'] = atomscores_new
df_new['bondscores'] = bondscores_new
df_new

,substrates,enzyme,atomscores,bondscores
0,NC(=O)c1nc(F)cnc1O,phase1.stable_oxygenation,"[0.028395801782608032, 0.001347571611404419, 2...","[0.00022098422050476074, 0.001357734203338623,..."
1,NC(=O)c1nc(F)cnc1O,phase1.unstable_oxygenation,"[0.0007294118404388428, 5.245208740234375e-06,...","[0.03473392128944397, 0.00991445779800415, 0.0..."
2,NC(=O)c1nc(F)cnc1O,phase1.dehydrogenation,"[0.007166236639022827, 1.4901161193847656e-06,...","[3.4183263778686523e-05, 0.0003910958766937256..."
3,NC(=O)c1nc(F)cnc1O,phase1.hydrolysis,"[5.59687614440918e-05, 2.592802047729492e-06, ...","[0.020581483840942383, 0.003480583429336548, 0..."
4,NC(=O)c1nc(F)cnc1O,phase1.reduction,"[0.001293569803237915, 0, 3.725290298461914e-0...","[0.0005504190921783447, 0.05507153272628784, 8..."
...,...,...,...,...
654,C#CC1(OC(C)=O)CCC2C3CCC4=CC(=NO)CCC4C3CCC21CC,phase1.stable_oxygenation,"[0.002860724925994873, 1.3113021850585938e-05,...","[4.2438507080078125e-05, 1.341104507446289e-06..."
655,C#CC1(OC(C)=O)CCC2C3CCC4=CC(=NO)CCC4C3CCC21CC,phase1.unstable_oxygenation,"[0.0005567073822021484, 1.9669532775878906e-06...","[0.0017003118991851807, 0.009026110172271729, ..."
656,C#CC1(OC(C)=O)CCC2C3CCC4=CC(=NO)CCC4C3CCC21CC,phase1.dehydrogenation,"[9.28342342376709e-05, 1.0222196578979492e-05,...","[3.1054019927978516e-05, 1.1026859283447266e-0..."
657,C#CC1(OC(C)=O)CCC2C3CCC4=CC(=NO)CCC4C3CCC21CC,phase1.hydrolysis,"[2.8252601623535156e-05, 3.6090612411499023e-0...","[0.002274543046951294, 0.0024235546588897705, ..."
658,C#CC1(OC(C)=O)CCC2C3CCC4=CC(=NO)CCC4C3CCC21CC,phase1.reduction,"[7.748603820800781e-07, 0, 0, 9.65595245361328...","[1.6003847122192383e-05, 2.682209014892578e-07..."

In [74]:
df_new.drop_duplicates(subset=['substrates','enzyme'],keep='first',inplace=True,ignore_index=True)

In [75]:
df_new

,substrates,enzyme,atomscores,bondscores
0,NC(=O)c1nc(F)cnc1O,phase1.stable_oxygenation,"[0.028395801782608032, 0.001347571611404419, 2...","[0.00022098422050476074, 0.001357734203338623,..."
1,NC(=O)c1nc(F)cnc1O,phase1.unstable_oxygenation,"[0.0007294118404388428, 5.245208740234375e-06,...","[0.03473392128944397, 0.00991445779800415, 0.0..."
2,NC(=O)c1nc(F)cnc1O,phase1.dehydrogenation,"[0.007166236639022827, 1.4901161193847656e-06,...","[3.4183263778686523e-05, 0.0003910958766937256..."
3,NC(=O)c1nc(F)cnc1O,phase1.hydrolysis,"[5.59687614440918e-05, 2.592802047729492e-06, ...","[0.020581483840942383, 0.003480583429336548, 0..."
4,NC(=O)c1nc(F)cnc1O,phase1.reduction,"[0.001293569803237915, 0, 3.725290298461914e-0...","[0.0005504190921783447, 0.05507153272628784, 8..."
...,...,...,...,...
379,CC(C)(O)c1ccccc1CCC(SCC1(CC(=O)O)CC1)c1cccc(C=...,phase1.stable_oxygenation,"[0.0875401496887207, 0, 0.0875401496887207, 0....","[0.0002409517765045166, 0.0002409517765045166,..."
380,CC(C)(O)c1ccccc1CCC(SCC1(CC(=O)O)CC1)c1cccc(C=...,phase1.unstable_oxygenation,"[2.3365020751953125e-05, 0, 2.3365020751953125...","[0.02907702326774597, 0.02907702326774597, 0.0..."
381,CC(C)(O)c1ccccc1CCC(SCC1(CC(=O)O)CC1)c1cccc(C=...,phase1.dehydrogenation,"[0.0025099217891693115, 0, 0.00250992178916931...","[0.00010332465171813965, 0.0001033246517181396..."
382,CC(C)(O)c1ccccc1CCC(SCC1(CC(=O)O)CC1)c1cccc(C=...,phase1.hydrolysis,"[1.7881393432617188e-06, 0, 1.7881393432617188...","[2.9027462005615234e-05, 2.9027462005615234e-0..."
383,CC(C)(O)c1ccccc1CCC(SCC1(CC(=O)O)CC1)c1cccc(C=...,phase1.reduction,"[0, 0, 0, 0.00020059943199157715, 0, 8.9406967...","[5.960464477539063e-08, 5.960464477539063e-08,..."

In [76]:
from collections import Counter


# 假设你有一个列表
example_list = df_new['substrates'].to_list()

# 使用 Counter 计数
element_count = Counter(example_list)

# 输出结果
for key, count in element_count.items():
    if count < 6:
        print(key)

In [77]:
from rdkit import Chem
def canonicalsmiles(smiles):
    mol = Chem.MolFromSmiles(smiles)
    smi_new = Chem.MolToSmiles(mol, isomericSmiles=False)
    return smi_new

In [78]:
# 输出的结果会失去立体构象
smiles_now = list(set(df_new['substrates'].to_list()))
smiles_now = list(map(canonicalsmiles,smiles_now))

df = pd.read_csv('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/predict_site_withec.csv')
smiles_shouldbe = df['SMILES'].to_list()
smiles_shouldbe = list(map(canonicalsmiles,smiles_shouldbe))

smiles_out = [i for i in smiles_shouldbe if i not in smiles_now]
for i in smiles_out:
    print(i)

In [79]:
df_new.to_pickle('xenosite_results.pickle')

In [80]:
df =  pd.read_pickle('xenosite_results.pickle')
df

,substrates,enzyme,atomscores,bondscores
0,NC(=O)c1nc(F)cnc1O,phase1.stable_oxygenation,"[0.028395801782608032, 0.001347571611404419, 2...","[0.00022098422050476074, 0.001357734203338623,..."
1,NC(=O)c1nc(F)cnc1O,phase1.unstable_oxygenation,"[0.0007294118404388428, 5.245208740234375e-06,...","[0.03473392128944397, 0.00991445779800415, 0.0..."
2,NC(=O)c1nc(F)cnc1O,phase1.dehydrogenation,"[0.007166236639022827, 1.4901161193847656e-06,...","[3.4183263778686523e-05, 0.0003910958766937256..."
3,NC(=O)c1nc(F)cnc1O,phase1.hydrolysis,"[5.59687614440918e-05, 2.592802047729492e-06, ...","[0.020581483840942383, 0.003480583429336548, 0..."
4,NC(=O)c1nc(F)cnc1O,phase1.reduction,"[0.001293569803237915, 0, 3.725290298461914e-0...","[0.0005504190921783447, 0.05507153272628784, 8..."
...,...,...,...,...
379,CC(C)(O)c1ccccc1CCC(SCC1(CC(=O)O)CC1)c1cccc(C=...,phase1.stable_oxygenation,"[0.0875401496887207, 0, 0.0875401496887207, 0....","[0.0002409517765045166, 0.0002409517765045166,..."
380,CC(C)(O)c1ccccc1CCC(SCC1(CC(=O)O)CC1)c1cccc(C=...,phase1.unstable_oxygenation,"[2.3365020751953125e-05, 0, 2.3365020751953125...","[0.02907702326774597, 0.02907702326774597, 0.0..."
381,CC(C)(O)c1ccccc1CCC(SCC1(CC(=O)O)CC1)c1cccc(C=...,phase1.dehydrogenation,"[0.0025099217891693115, 0, 0.00250992178916931...","[0.00010332465171813965, 0.0001033246517181396..."
382,CC(C)(O)c1ccccc1CCC(SCC1(CC(=O)O)CC1)c1cccc(C=...,phase1.hydrolysis,"[1.7881393432617188e-06, 0, 1.7881393432617188...","[2.9027462005615234e-05, 2.9027462005615234e-0..."
383,CC(C)(O)c1ccccc1CCC(SCC1(CC(=O)O)CC1)c1cccc(C=...,phase1.reduction,"[0, 0, 0, 0.00020059943199157715, 0, 8.9406967...","[5.960464477539063e-08, 5.960464477539063e-08,..."

In [90]:
df =  pd.read_pickle('xenosite_results.pickle')
atomscores = df['atomscores'].to_list()

# 使用字典推导式生成字典
atomscores = [{idx: score for idx, score in enumerate(i)} for i in atomscores]
df['atomscores'] = atomscores

def group_by_column_to_dict(df, col_A, col_B):
    # 使用 groupby 按 col_A 分组，并将每组的 col_B 合并为一个列表
    result = df.groupby(col_A)[col_B].apply(list).to_dict()
    return result
def sum_ranks(dicts):
    # 获取所有的原子序号
    all_keys = set(key for d in dicts for key in d)
    
    # 创建一个新的字典，将原子序号的值加在一起
    result = {key: sum(d.get(key, 0) for d in dicts) for key in all_keys}
    
    return result
def assign_ranks(atom_scores):
    # 按分数降序排序，并获取排序后的原子序号
    sorted_atoms = sorted(atom_scores.items(), key=lambda x: x[1], reverse=True)
    
    # 创建一个字典，保存原子序号对应的排名
    rank_dict = {}
    for rank, (atom, _) in enumerate(sorted_atoms):
        rank_dict[atom] = rank + 1
    
    # 保持原子序号从小到大的顺序，并更新为对应的排名
    ranked_atoms = {atom: rank_dict[atom] for atom in sorted(atom_scores)}
    
    return ranked_atoms

atomscores = df['atomscores'].to_list()
atomscores = list(map(assign_ranks,atomscores))
df['atomscores'] = atomscores
# df.to_pickle('xenosite_results_withrank.pickle')
# 示例
result = group_by_column_to_dict(df, 'substrates', 'atomscores')
result_new = {}
for i,j in result.items():
    j = sum_ranks(j)
    result_new[i] = j

print(result_new)

{'C#CC1(OC(C)=O)CCC2C3CCC4=CC(=NO)CCC4C3CCC21CC': {0: 65, 1: 107, 2: 138, 3: 77, 4: 107, 5: 74, 6: 85, 7: 70, 8: 62, 9: 80, 10: 92, 11: 61, 12: 77, 13: 119, 14: 64, 15: 129, 16: 38, 17: 49, 18: 67, 19: 55, 20: 98, 21: 65, 22: 84, 23: 84, 24: 159, 25: 83, 26: 79}, 'CC(C)(O)c1ccccc1CCC(SCC1(CC(=O)O)CC1)c1cccc(C=Cc2ccc3ccc(Cl)cc3n2)c1': {0: 68, 1: 204, 2: 75, 3: 36, 4: 184, 5: 112, 6: 85, 7: 71, 8: 116, 9: 195, 10: 92, 11: 88, 12: 108, 13: 34, 14: 116, 15: 202, 16: 112, 17: 152, 18: 165, 19: 58, 20: 94, 21: 100, 22: 202, 23: 115, 24: 135, 25: 82, 26: 192, 27: 75, 28: 78, 29: 215, 30: 135, 31: 93, 32: 199, 33: 73, 34: 120, 35: 201, 36: 215, 37: 141, 38: 225, 39: 83, 40: 120}, 'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1': {0: 46, 1: 63, 2: 53, 3: 74, 4: 30, 5: 73, 6: 137, 7: 68, 8: 80, 9: 143, 10: 137, 11: 85, 12: 65, 13: 64, 14: 99, 15: 135, 16: 85, 17: 86, 18: 92, 19: 46, 20: 68, 21: 66, 22: 72, 23: 76, 24: 89, 25: 74}, 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C': {0: 56, 1: 58, 2: 64, 3: 22, 4: 108, 5: 65, 6: 39, 7: 45, 8: 65, 9: 102, 10: 22, 11: 108, 12: 71, 13: 51, 14: 47, 15: 73, 16: 118, 17: 18, 18: 61, 19: 67}, 'CC(NC(C)(C)C)C(=O)c1cccc(Cl)c1': {0: 36, 1: 45, 2: 15, 3: 82, 4: 30, 5: 36, 6: 42, 7: 63, 8: 43, 9: 82, 10: 46, 11: 37, 12: 37, 13: 83, 14: 84, 15: 55}, 'CC(Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)ccc(F)c1Cl': {0: 64, 1: 73, 2: 52, 3: 132, 4: 78, 5: 118, 6: 128, 7: 92, 8: 74, 9: 65, 10: 67, 11: 53, 12: 58, 13: 15, 14: 64, 15: 61, 16: 94, 17: 100, 18: 63, 19: 150, 20: 22, 21: 140, 22: 139, 23: 143, 24: 82, 25: 49, 26: 155, 27: 151, 28: 149, 29: 159}, 'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1': {0: 120, 1: 289, 2: 127, 3: 125, 4: 149, 5: 216, 6: 160, 7: 57, 8: 113, 9: 154, 10: 61, 11: 294, 12: 177, 13: 161, 14: 296, 15: 222, 16: 168, 17: 65, 18: 170, 19: 182, 20: 188, 21: 271, 22: 187, 23: 168, 24: 305, 25: 48, 26: 168, 27: 146, 28: 127, 29: 94, 30: 98, 31: 100, 32: 135, 33: 309, 34: 108, 35: 212, 36: 218, 37: 190, 38: 278, 39: 131, 40: 298, 41: 246, 42: 123, 43: 314, 44: 71, 45: 192, 46: 172, 47: 311, 48: 159, 49: 228, 50: 184, 51: 147, 52: 261, 53: 314, 54: 174, 55: 184, 56: 301, 57: 317, 58: 192, 59: 184, 60: 187}, 'CC1(C)SC2C(NC(=O)C(N)c3ccc(O)cc3)C(=O)N2C1C(=O)O': {0: 57, 1: 140, 2: 64, 3: 44, 4: 83, 5: 95, 6: 39, 7: 106, 8: 78, 9: 77, 10: 27, 11: 124, 12: 71, 13: 56, 14: 120, 15: 27, 16: 62, 17: 77, 18: 131, 19: 73, 20: 50, 21: 88, 22: 110, 23: 99, 24: 52}, 'CC12C=CC(=O)C(Cl)=C1CCC1C2CCC2(C)C1CCC2(C)O': {0: 51, 1: 114, 2: 50, 3: 43, 4: 95, 5: 54, 6: 89, 7: 111, 8: 91, 9: 58, 10: 51, 11: 74, 12: 55, 13: 67, 14: 68, 15: 130, 16: 67, 17: 59, 18: 57, 19: 42, 20: 136, 21: 69, 22: 25}, 'CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O)C(=O)COP(=O)(O)O': {0: 72, 1: 83, 2: 74, 3: 87, 4: 108, 5: 87, 6: 86, 7: 128, 8: 68, 9: 132, 10: 82, 11: 56, 12: 71, 13: 165, 14: 76, 15: 172, 16: 168, 17: 104, 18: 38, 19: 99, 20: 177, 21: 101, 22: 187, 23: 41, 24: 125, 25: 103, 26: 109, 27: 84, 28: 80, 29: 109, 30: 45, 31: 51}, 'CC1CCC2C(C)C(OC(=O)CCC(=O)O)OC3OC4(C)CCC1C32OO4': {0: 53, 1: 70, 2: 60, 3: 74, 4: 89, 5: 82, 6: 70, 7: 76, 8: 84, 9: 106, 10: 85, 11: 81, 12: 70, 13: 106, 14: 105, 15: 42, 16: 78, 17: 69, 18: 77, 19: 152, 20: 78, 21: 83, 22: 89, 23: 107, 24: 160, 25: 72, 26: 50}, 'CC1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12': {0: 47, 1: 65, 2: 53, 3: 12, 4: 44, 5: 59, 6: 56, 7: 42, 8: 64, 9: 67, 10: 73, 11: 100, 12: 65, 13: 68, 14: 45, 15: 115, 16: 70, 17: 42, 18: 78, 19: 120, 20: 118, 21: 115}, 'CC1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23': {0: 38, 1: 66, 2: 62, 3: 51, 4: 113, 5: 129, 6: 27, 7: 62, 8: 46, 9: 22, 10: 63, 11: 53, 12: 71, 13: 127, 14: 137, 15: 71, 16: 133, 17: 124, 18: 61, 19: 122, 20: 94, 21: 104, 22: 44, 23: 93, 24: 62, 25: 131}, 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O': {0: 45, 1: 39, 2: 92, 3: 80, 4: 54, 5: 34, 6: 26, 7: 40, 8: 60, 9: 75, 10: 52, 11: 14, 12: 90, 13: 57, 14: 20, 15: 82, 16: 58}, 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1': {0: 37, 1: 51, 2: 52, 3: 41, 4: 105, 5: 45, 6: 31, 7: 36, 8: 65, 9: 99, 10: 55, 11: 64, 12: 55, 13: 106, 14: 52, 15: 99, 16: 109, 17: 114, 18: 19, 19: 107, 20: 118, 21: 58}, 'CCCC1CC(C(=O)NC(C(C)Cl)C2OC(SC)C(O)C(O)C2O)N(C)C1': {0: 67, 1: 82, 2: 83, 3: 92, 4: 85, 5: 95, 6: 129, 7: 97, 8: 51, 9: 128, 10: 102, 11: 92, 12: 148, 13: 88, 14: 101, 15: 92, 16: 38, 17: 104, 18: 57, 19: 38, 20: 73, 21: 40, 22: 72, 23: 50, 24: 42, 25: 115, 26: 107}, 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1': {0: 33, 1: 53, 2: 55, 3: 64, 4: 67, 5: 72, 6: 61, 7: 64, 8: 115, 9: 70, 10: 68, 11: 119, 12: 86, 13: 85, 14: 130, 15: 42, 16: 60, 17: 26, 18: 66, 19: 32, 20: 74, 21: 76}, 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1': {0: 109, 1: 105, 2: 123, 3: 141, 4: 27, 5: 213, 6: 135, 7: 146, 8: 216, 9: 194, 10: 173, 11: 146, 12: 157, 13: 133, 14: 131, 15: 103, 16: 98, 17: 122, 18: 85, 19: 68, 20: 86, 21: 72, 22: 93, 23: 128, 24: 108, 25: 115, 26: 135, 27: 117, 28: 122, 29: 141, 30: 130, 31: 134, 32: 148, 33: 136, 34: 133, 35: 149, 36: 116, 37: 113, 38: 143, 39: 139, 40: 171, 41: 164}, 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1': {0: 37, 1: 62, 2: 59, 3: 80, 4: 129, 5: 81, 6: 141, 7: 68, 8: 64, 9: 64, 10: 85, 11: 149, 12: 146, 13: 105, 14: 75, 15: 144, 16: 76, 17: 139, 18: 153, 19: 155, 20: 62, 21: 79, 22: 90, 23: 20, 24: 76, 25: 72, 26: 83, 27: 79, 28: 154, 29: 167, 30: 82}, 'CCCSc1nc(NC2CC2c2ccc(F)c(F)c2)c2nnn(C3CC(OCCO)C(O)C3O)c2n1': {0: 58, 1: 78, 2: 75, 3: 81, 4: 170, 5: 122, 6: 169, 7: 44, 8: 113, 9: 82, 10: 92, 11: 159, 12: 94, 13: 80, 14: 168, 15: 166, 16: 178, 17: 176, 18: 97, 19: 191, 20: 91, 21: 136, 22: 137, 23: 113, 24: 104, 25: 103, 26: 87, 27: 96, 28: 94, 29: 29, 30: 71, 31: 43, 32: 108, 33: 46, 34: 206, 35: 139}, 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC': {0: 42, 1: 46, 2: 21, 3: 52, 4: 50, 5: 49, 6: 63, 7: 25, 8: 86, 9: 60, 10: 101, 11: 65, 12: 105, 13: 106, 14: 104, 15: 11, 16: 53, 17: 103, 18: 50, 19: 68}, 'CCN(CC)CCOC(=O)c1ccc(N)cc1': {0: 46, 1: 45, 2: 19, 3: 51, 4: 54, 5: 61, 6: 57, 7: 51, 8: 83, 9: 55, 10: 96, 11: 52, 12: 40, 13: 95, 14: 9, 15: 46, 16: 58}, 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1': {0: 89, 1: 107, 2: 53, 3: 211, 4: 134, 5: 192, 6: 199, 7: 117, 8: 113, 9: 190, 10: 118, 11: 42, 12: 93, 13: 61, 14: 83, 15: 67, 16: 101, 17: 119, 18: 129, 19: 137, 20: 219, 21: 193, 22: 122, 23: 49, 24: 130, 25: 218, 26: 194, 27: 122, 28: 128, 29: 202, 30: 116, 31: 50, 32: 226, 33: 119, 34: 216, 35: 124, 36: 144, 37: 109, 38: 86, 39: 87, 40: 92, 41: 117}, 'CCNC1CC(C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21': {0: 38, 1: 44, 2: 18, 3: 52, 4: 47, 5: 52, 6: 48, 7: 66, 8: 59, 9: 65, 10: 93, 11: 82, 12: 84, 13: 58, 14: 25, 15: 66, 16: 72, 17: 69, 18: 102}, 'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2': {0: 74, 1: 61, 2: 83, 3: 119, 4: 89, 5: 25, 6: 142, 7: 82, 8: 90, 9: 139, 10: 143, 11: 99, 12: 52, 13: 130, 14: 87, 15: 93, 16: 25, 17: 78, 18: 72, 19: 85, 20: 79, 21: 164, 22: 89, 23: 58, 24: 60, 25: 72, 26: 154, 27: 83, 28: 83}, 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12': {0: 66, 1: 65, 2: 82, 3: 103, 4: 82, 5: 140, 6: 126, 7: 79, 8: 28, 9: 133, 10: 68, 11: 50, 12: 50, 13: 56, 14: 75, 15: 56, 16: 79, 17: 146, 18: 88, 19: 141, 20: 155, 21: 156, 22: 25, 23: 138, 24: 83, 25: 38, 26: 72, 27: 78, 28: 152}, 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1': {0: 70, 1: 32, 2: 76, 3: 126, 4: 88, 5: 85, 6: 83, 7: 118, 8: 94, 9: 82, 10: 145, 11: 80, 12: 68, 13: 146, 14: 77, 15: 121, 16: 94, 17: 153, 18: 74, 19: 91, 20: 155, 21: 23, 22: 147, 23: 22, 24: 21, 25: 99, 26: 80, 27: 74, 28: 86}, 'CN(C)CCCN1c2ccccc2CCc2ccccc21': {0: 56, 1: 24, 2: 62, 3: 59, 4: 64, 5: 63, 6: 26, 7: 112, 8: 70, 9: 40, 10: 43, 11: 57, 12: 109, 13: 60, 14: 66, 15: 117, 16: 63, 17: 49, 18: 44, 19: 76, 20: 126}, 'CN(C)c1ccc(O)c2c1CC1CC3C(N(C)C)C(O)=C(C(N)=O)C(=O)C3(O)C(O)=C1C2=O': {0: 72, 1: 30, 2: 78, 3: 159, 4: 75, 5: 79, 6: 154, 7: 35, 8: 160, 9: 158, 10: 84, 11: 91, 12: 84, 13: 73, 14: 105, 15: 54, 16: 80, 17: 86, 18: 147, 19: 62, 20: 158, 21: 142, 22: 35, 23: 99, 24: 119, 25: 110, 26: 195, 27: 41, 28: 152, 29: 60, 30: 145, 31: 144, 32: 100}, 'CN1CCc2cccc3c2C1Cc1ccc(O)c(O)c1-3': {0: 44, 1: 21, 2: 34, 3: 41, 4: 91, 5: 45, 6: 50, 7: 58, 8: 94, 9: 94, 10: 54, 11: 54, 12: 97, 13: 69, 14: 39, 15: 97, 16: 22, 17: 110, 18: 32, 19: 114}, 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21': {0: 66, 1: 21, 2: 114, 3: 71, 4: 48, 5: 58, 6: 62, 7: 113, 8: 101, 9: 65, 10: 28, 11: 65, 12: 52, 13: 111, 14: 121, 15: 37, 16: 129, 17: 50, 18: 34, 19: 57, 20: 51, 21: 127, 22: 75}, 'CNC(=O)c1ccccc1Sc1ccc2c(C=Cc3ccccn3)n[nH]c2c1': {0: 71, 1: 27, 2: 118, 3: 78, 4: 145, 5: 72, 6: 76, 7: 60, 8: 92, 9: 137, 10: 35, 11: 141, 12: 106, 13: 66, 14: 144, 15: 143, 16: 54, 17: 51, 18: 154, 19: 57, 20: 45, 21: 54, 22: 95, 23: 48, 24: 92, 25: 48, 26: 141, 27: 86}, 'CNC(C)C(O)c1ccccc1': {0: 45, 1: 17, 2: 45, 3: 44, 4: 44, 5: 18, 6: 71, 7: 44, 8: 29, 9: 26, 10: 35, 11: 50}, 'CNCCC(Oc1ccccc1C)c1ccccc1': {0: 51, 1: 17, 2: 52, 3: 67, 4: 69, 5: 51, 6: 107, 7: 72, 8: 61, 9: 34, 10: 47, 11: 103, 12: 57, 13: 108, 14: 63, 15: 38, 16: 30, 17: 44, 18: 69}, 'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1': {0: 52, 1: 14, 2: 52, 3: 116, 4: 73, 5: 119, 6: 122, 7: 57, 8: 45, 9: 34, 10: 54, 11: 119, 12: 122, 13: 50, 14: 64, 15: 68, 16: 74, 17: 120, 18: 56, 19: 71, 20: 74, 21: 59, 22: 95, 23: 90}, 'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C': {0: 77, 1: 74, 2: 162, 3: 155, 4: 144, 5: 80, 6: 77, 7: 157, 8: 75, 9: 163, 10: 22, 11: 85, 12: 70, 13: 102, 14: 108, 15: 75, 16: 78, 17: 162, 18: 73, 19: 115, 20: 182, 21: 71, 22: 104, 23: 66, 24: 172, 25: 85, 26: 32, 27: 174, 28: 95, 29: 121, 30: 171, 31: 201, 32: 78, 33: 84, 34: 90}, 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC': {0: 47, 1: 42, 2: 92, 3: 49, 4: 95, 5: 43, 6: 102, 7: 68, 8: 54, 9: 104, 10: 16, 11: 63, 12: 111, 13: 13, 14: 55, 15: 105, 16: 48, 17: 62, 18: 104, 19: 49, 20: 64}, 'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O': {0: 68, 1: 69, 2: 129, 3: 80, 4: 144, 5: 54, 6: 92, 7: 79, 8: 135, 9: 71, 10: 131, 11: 59, 12: 72, 13: 141, 14: 23, 15: 130, 16: 89, 17: 22, 18: 70, 19: 53, 20: 59, 21: 153, 22: 159, 23: 72, 24: 161, 25: 73, 26: 160, 27: 133, 28: 29, 29: 80}, 'COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1': {0: 71, 1: 59, 2: 129, 3: 54, 4: 73, 5: 122, 6: 69, 7: 72, 8: 69, 9: 32, 10: 77, 11: 83, 12: 34, 13: 130, 14: 87, 15: 61, 16: 137, 17: 34, 18: 143, 19: 23, 20: 85, 21: 80, 22: 87, 23: 79, 24: 60}, 'COc1ccc(S(=O)(=O)N2Cc3[nH]c4ccccc4c3CC2C(N)=O)cc1': {0: 63, 1: 57, 2: 127, 3: 63, 4: 82, 5: 126, 6: 69, 7: 86, 8: 92, 9: 25, 10: 76, 11: 142, 12: 40, 13: 145, 14: 68, 15: 51, 16: 69, 17: 67, 18: 142, 19: 141, 20: 75, 21: 84, 22: 121, 23: 26, 24: 73, 25: 88, 26: 70}, 'COc1ccc2ccc(=O)oc2c1CC=C(C)C': {0: 39, 1: 36, 2: 87, 3: 52, 4: 43, 5: 89, 6: 38, 7: 37, 8: 90, 9: 45, 10: 59, 11: 91, 12: 85, 13: 46, 14: 29, 15: 66, 16: 44, 17: 50}, 'COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc(-c2ncccn2)nc1OCCO': {0: 83, 1: 73, 2: 174, 3: 77, 4: 71, 5: 77, 6: 97, 7: 187, 8: 102, 9: 195, 10: 192, 11: 38, 12: 102, 13: 125, 14: 131, 15: 176, 16: 98, 17: 106, 18: 179, 19: 210, 20: 74, 21: 80, 22: 86, 23: 117, 24: 104, 25: 142, 26: 201, 27: 202, 28: 70, 29: 127, 30: 110, 31: 134, 32: 76, 33: 114, 34: 215, 35: 100, 36: 110, 37: 94, 38: 31}, 'CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1': {0: 67, 1: 80, 2: 109, 3: 115, 4: 72, 5: 81, 6: 36, 7: 85, 8: 164, 9: 110, 10: 117, 11: 178, 12: 195, 13: 97, 14: 118, 15: 181, 16: 97, 17: 135, 18: 111, 19: 186, 20: 20, 21: 192, 22: 89, 23: 84, 24: 196, 25: 68, 26: 95, 27: 184, 28: 94, 29: 67, 30: 69, 31: 198, 32: 197, 33: 84, 34: 193, 35: 213, 36: 135, 37: 210, 38: 85, 39: 113}, 'Cc1cc(N2CCN(C3CNC(C(=O)N4CCSC4)C3)CC2)n(-c2ccccc2)n1': {0: 92, 1: 155, 2: 103, 3: 158, 4: 40, 5: 95, 6: 72, 7: 45, 8: 108, 9: 92, 10: 39, 11: 106, 12: 138, 13: 98, 14: 51, 15: 93, 16: 80, 17: 61, 18: 109, 19: 101, 20: 86, 21: 111, 22: 100, 23: 171, 24: 87, 25: 62, 26: 72, 27: 68, 28: 94, 29: 103}, 'Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1': {0: 59, 1: 93, 2: 73, 3: 114, 4: 110, 5: 88, 6: 20, 7: 116, 8: 56, 9: 42, 10: 50, 11: 65, 12: 116, 13: 40, 14: 103, 15: 31, 16: 65, 17: 52, 18: 22, 19: 70, 20: 59, 21: 74}, 'Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CCC2C)c1': {0: 57, 1: 137, 2: 68, 3: 74, 4: 151, 5: 75, 6: 74, 7: 75, 8: 81, 9: 82, 10: 158, 11: 142, 12: 85, 13: 39, 14: 84, 15: 78, 16: 32, 17: 151, 18: 77, 19: 162, 20: 88, 21: 153, 22: 166, 23: 93, 24: 73, 25: 162, 26: 113, 27: 97, 28: 76, 29: 100, 30: 80, 31: 85}, 'Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)C=Cc3ccc(O)cc3)cc2)cc1': {0: 66, 1: 132, 2: 72, 3: 82, 4: 143, 5: 78, 6: 89, 7: 95, 8: 25, 9: 156, 10: 89, 11: 62, 12: 144, 13: 114, 14: 74, 15: 56, 16: 47, 17: 154, 18: 62, 19: 54, 20: 148, 21: 29, 22: 60, 23: 68, 24: 68, 25: 97, 26: 92, 27: 80}, 'Cc1cccc(C)c1OCC(=O)NC(Cc1ccccc1)C(O)CC(Cc1ccccc1)NC(=O)C(C(C)C)N1CCCNC1=O': {0: 109, 1: 218, 2: 137, 3: 133, 4: 144, 5: 227, 6: 120, 7: 247, 8: 108, 9: 159, 10: 200, 11: 146, 12: 61, 13: 155, 14: 129, 15: 240, 16: 140, 17: 99, 18: 101, 19: 106, 20: 146, 21: 130, 22: 58, 23: 137, 24: 175, 25: 134, 26: 241, 27: 140, 28: 99, 29: 96, 30: 105, 31: 148, 32: 66, 33: 222, 34: 141, 35: 177, 36: 147, 37: 117, 38: 123, 39: 68, 40: 147, 41: 104, 42: 133, 43: 40, 44: 256, 45: 157}, 'Clc1ccc(CCCOCCCN2CCCCC2)cc1': {0: 92, 1: 104, 2: 55, 3: 46, 4: 101, 5: 63, 6: 70, 7: 47, 8: 44, 9: 50, 10: 74, 11: 69, 12: 22, 13: 64, 14: 60, 15: 48, 16: 66, 17: 72, 18: 52, 19: 61}, 'Clc1ccccc1CN1CCc2sccc2C1': {0: 84, 1: 87, 2: 47, 3: 27, 4: 34, 5: 41, 6: 82, 7: 41, 8: 12, 9: 40, 10: 49, 11: 84, 12: 57, 13: 44, 14: 49, 15: 90, 16: 50}, 'Cn1c(=O)c2c(ncn2C)n(C)c1=O': {0: 36, 1: 24, 2: 65, 3: 39, 4: 65, 5: 67, 6: 34, 7: 48, 8: 18, 9: 41, 10: 31, 11: 39, 12: 82, 13: 41}, 'Cn1nnc(-c2ccc(-c3ccc(N4CC(CO)OC4=O)cc3F)cn2)n1': {0: 41, 1: 81, 2: 89, 3: 76, 4: 128, 5: 134, 6: 68, 7: 58, 8: 124, 9: 116, 10: 63, 11: 59, 12: 138, 13: 30, 14: 67, 15: 67, 16: 52, 17: 27, 18: 74, 19: 115, 20: 80, 21: 67, 22: 137, 23: 146, 24: 99, 25: 50, 26: 82}, 'NC(=O)c1cn(Cc2c(F)cccc2F)nn1': {0: 12, 1: 61, 2: 38, 3: 76, 4: 39, 5: 39, 6: 37, 7: 74, 8: 77, 9: 85, 10: 30, 11: 26, 12: 36, 13: 84, 14: 92, 15: 61, 16: 51}, 'NC(=O)c1nc(F)cnc1O': {0: 11, 1: 37, 2: 31, 3: 51, 4: 21, 5: 55, 6: 60, 7: 34, 8: 27, 9: 55, 10: 14}, 'NC(Cc1cc(O)c(O)cc1F)C(=O)O': {0: 19, 1: 39, 2: 38, 3: 64, 4: 43, 5: 69, 6: 19, 7: 74, 8: 15, 9: 34, 10: 77, 11: 82, 12: 62, 13: 54, 14: 31}, 'NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1': {0: 17, 1: 99, 2: 23, 3: 38, 4: 98, 5: 73, 6: 101, 7: 68, 8: 29, 9: 62, 10: 66, 11: 102, 12: 26, 13: 43, 14: 56, 15: 36, 16: 81, 17: 87, 18: 65, 19: 90}, 'O=C(NC(CO)C(O)c1ccc([N+](=O)[O-])cc1)C(Cl)Cl': {0: 58, 1: 83, 2: 23, 3: 63, 4: 45, 5: 22, 6: 48, 7: 28, 8: 93, 9: 59, 10: 51, 11: 102, 12: 36, 13: 71, 14: 77, 15: 57, 16: 67, 17: 63, 18: 104, 19: 110}, 'O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F': {0: 72, 1: 90, 2: 24, 3: 66, 4: 46, 5: 34, 6: 22, 7: 117, 8: 62, 9: 73, 10: 119, 11: 79, 12: 70, 13: 82, 14: 77, 15: 116, 16: 25, 17: 123, 18: 56, 19: 44, 20: 111, 21: 126, 22: 51, 23: 131, 24: 134}, 'O=C(O)CCC(=O)OCC(NC(=O)C(Cl)Cl)C(O)c1ccc([N+](=O)[O-])cc1': {0: 101, 1: 96, 2: 39, 3: 65, 4: 75, 5: 103, 6: 78, 7: 67, 8: 70, 9: 81, 10: 30, 11: 112, 12: 77, 13: 82, 14: 145, 15: 151, 16: 82, 17: 29, 18: 134, 19: 72, 20: 61, 21: 139, 22: 44, 23: 92, 24: 98, 25: 67, 26: 78}, 'O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O': {0: 238, 1: 229, 2: 128, 3: 268, 4: 161, 5: 285, 6: 100, 7: 283, 8: 264, 9: 195, 10: 170, 11: 176, 12: 273, 13: 204, 14: 283, 15: 246, 16: 261, 17: 134, 18: 178, 19: 306, 20: 106, 21: 306, 22: 234, 23: 186, 24: 319, 25: 311, 26: 156, 27: 209, 28: 178, 29: 142, 30: 132, 31: 44, 32: 124, 33: 56, 34: 139, 35: 64, 36: 152, 37: 88, 38: 173, 39: 175, 40: 199, 41: 279, 42: 285, 43: 207, 44: 185, 45: 187, 46: 329, 47: 162, 48: 225, 49: 184, 50: 148, 51: 148, 52: 50, 53: 131, 54: 62, 55: 146, 56: 70, 57: 158, 58: 94, 59: 345, 60: 256, 61: 192}, 'O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1': {0: 50, 1: 84, 2: 50, 3: 19, 4: 74, 5: 92, 6: 41, 7: 38, 8: 20, 9: 44, 10: 47, 11: 99, 12: 65, 13: 95, 14: 100, 15: 35, 16: 67, 17: 104, 18: 16}, 'O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O': {0: 55, 1: 90, 2: 20, 3: 103, 4: 60, 5: 39, 6: 97, 7: 104, 8: 69, 9: 108, 10: 85, 11: 103, 12: 44, 13: 44, 14: 25, 15: 50, 16: 50, 17: 26, 18: 65, 19: 23}, 'O=P1(NCCCl)OCCCN1CCCl': {0: 54, 1: 39, 2: 23, 3: 46, 4: 41, 5: 70, 6: 51, 7: 22, 8: 42, 9: 40, 10: 25, 11: 47, 12: 51, 13: 79}, 'OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1': {0: 27, 1: 65, 2: 59, 3: 70, 4: 71, 5: 93, 6: 38, 7: 66, 8: 79, 9: 38, 10: 94, 11: 140, 12: 86, 13: 58, 14: 48, 15: 64, 16: 94, 17: 143, 18: 86, 19: 69, 20: 142, 21: 140, 22: 75, 23: 92, 24: 90, 25: 79}}

In [ ]:
df_total = pd.read_pickle('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/output_65_site_truth_correct_withatomidx_noenzyme.pickle')
substrates = df_total['substrates'].to_list()
xenosite_results = [result_new[i] for i in substrates]
df_total['xenosite_results'] = xenosite_results
df_total