In [5]:
import pandas as pd
import os

In [4]:
df_substrates = pd.read_csv('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/predict_site_withec.csv')
substrates = df_substrates['SMILES'].to_list()
dict_idx2sub = dict(zip(list(range(len(substrates))),substrates))
dict_idx2sub

{0: 'C#C[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=C/C(=N/O)CC[C@@H]4[C@H]3CC[C@@]21CC',
 1: 'CC(C)(O)c1ccccc1CC[C@@H](SCC1(CC(=O)O)CC1)c1cccc(/C=C/c2ccc3ccc(Cl)cc3n2)c1',
 2: 'CC(C)CNCc1ccc(-c2ccccc2S(=O)(=O)N2CCCC2)cc1',
 3: 'CC(CN1c2ccccc2Sc2ccccc21)N(C)C',
 4: 'CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)=C(c2ccc(Cl)cc2)C1',
 5: 'CC1(C)S[C@@H]2[C@H](NC(=O)[C@H](N)c3ccc(O)cc3)C(=O)N2[C@H]1C(=O)O',
 6: 'CCC1(c2ccccc2)C(=O)NC(=O)NC1=O',
 7: 'CCC1Oc2ccccc2C1C(=O)c1cc(Br)c(O)c(Br)c1',
 8: 'CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1',
 9: 'CCCCNc1ccc(C(=O)OCCOCCOCCOCCOCCOCCOCCOCCOCCOC)cc1',
 10: 'CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1',
 11: 'CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([C@@H]3C[C@H](OCCO)[C@@H](O)[C@H]3O)c2n1',
 12: 'CCC[C@@H]1C[C@@H](C(=O)NC(C(C)Cl)[C@H]2O[C@H](SC)[C@H](O)[C@@H](O)[C@H]2O)N(C)C1',
 13: 'CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC',
 14: 'CCN(CC)CCOC(=O)c1ccc(N)cc1',
 15: 'CCN(c1cc(-c2ccc(CN3CCOCC3)cc2)cc(C(=O)NCc2c(C)cc(C)[nH]c2=O)c1C)C1CCOCC1',
 16: 'CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21',
 17: 'CCOC(=O)Nc1ccc2c(c1)N(C(=O)CN(CC)CC)c1ccccc1CC2',
 18: 'CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)C)c12',
 19: 'CN(C)C(=O)COC(=O)Cc1ccc(OC(=O)c2ccc(NC(=N)N)cc2)cc1',
 20: 'CN(C)CCCN1c2ccccc2CCc2ccccc21',
 21: 'CN(C)c1ccc(O)c2c1C[C@H]1C[C@H]3[C@H](N(C)C)C(O)=C(C(N)=O)C(=O)[C@@]3(O)C(O)=C1C2=O',
 22: 'CN1CCc2cccc3c2[C@H]1Cc1ccc(O)c(O)c1-3',
 23: 'CN1c2ccccc2C(=O)N2CCc3c([nH]c4ccccc34)C21',
 24: 'CNC(=O)c1ccccc1Sc1ccc2c(/C=C/c3ccccn3)n[nH]c2c1',
 25: 'CNCC[C@@H](Oc1ccccc1C)c1ccccc1',
 26: 'CNCc1cc(-c2ccccc2F)n(S(=O)(=O)c2cccnc2)c1',
 27: 'CN[C@@H](C)[C@@H](O)c1ccccc1',
 28: 'CN[C@@H](C)[C@H](O)c1ccccc1',
 29: 'COc1c(-c2ccc3cc(NS(C)(=O)=O)ccc3c2)cc(-n2ccc(=O)[nH]c2=O)cc1C(C)(C)C',
 30: 'COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC',
 31: 'COc1cc2nccc(Oc3ccc(NC(=O)NC4CC4)c(Cl)c3)c2cc1C(N)=O',
 32: 'COc1ccc(CC(C)NCC(O)c2ccc(O)c(NC=O)c2)cc1',
 33: 'COc1ccc(S(=O)(=O)N2Cc3[nH]c4ccccc4c3CC2C(N)=O)cc1',
 34: 'COc1ccc2ccc(=O)oc2c1CC=C(C)C',
 35: 'COc1ccccc1Oc1c(NS(=O)(=O)c2ccc(C(C)(C)C)cc2)nc(-c2ncccn2)nc1OCCO',
 36: 'CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1',
 37: 'C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)ccc(F)c1Cl',
 38: 'C[C@@H]1CC[C@H]2[C@@H](C)[C@H](OC(=O)CCC(=O)O)O[C@@H]3O[C@@]4(C)CC[C@@H]1[C@@]23OO4',
 39: 'C[C@H](NC(C)(C)C)C(=O)c1cccc(Cl)c1',
 40: 'C[C@H]1CNCCCN1S(=O)(=O)c1cccc2cncc(F)c12',
 41: 'C[C@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23',
 42: 'C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)COP(=O)(O)O',
 43: 'C[C@]12C=CC(=O)C(Cl)=C1CC[C@H]1[C@H]2CC[C@]2(C)[C@@H]1CC[C@]2(C)O',
 44: 'Cc1cc(N2CCN([C@H]3CN[C@H](C(=O)N4CCSC4)C3)CC2)n(-c2ccccc2)n1',
 45: 'Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1',
 46: 'Cc1ccc(-n2nccn2)c(C(=O)N2CCN(c3nc4cc(Cl)ccc4o3)CCC2C)c1',
 47: 'Cc1ccc(S(=O)(=O)Nc2ccc(C(=O)/C=C/c3ccc(O)cc3)cc2)cc1',
 48: 'Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)C[C@H](Cc1ccccc1)NC(=O)[C@H](C(C)C)N1CCCNC1=O',
 49: 'Clc1ccc(CCCOCCCN2CCCCC2)cc1',
 50: 'Clc1ccccc1CN1CCc2sccc2C1',
 51: 'Cn1c(=O)c2c(ncn2C)n(C)c1=O',
 52: 'Cn1nnc(-c2ccc(-c3ccc(N4C[C@H](CO)OC4=O)cc3F)cn2)n1',
 53: 'NC(=O)c1cn(Cc2c(F)cccc2F)nn1',
 54: 'NC(=O)c1nc(F)cnc1O',
 55: 'NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1',
 56: 'N[C@@H](Cc1cc(O)c(O)cc1[18F])C(=O)O',
 57: 'O=C(NOCCO)c1ccc2cncn2c1Nc1ccc(I)cc1F',
 58: 'O=C(N[C@H](CO)[C@H](O)c1ccc([N+](=O)[O-])cc1)C(Cl)Cl',
 59: 'O=C(O)CCC(=O)OC[C@@H](NC(=O)C(Cl)Cl)[C@H](O)c1ccc([N+](=O)[O-])cc1',
 60: 'O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=O)c3c(OC4OC(CO)C(O)C(O)C4O)cccc31)c1cccc(OC3OC(CO)C(O)C(O)C3O)c1C2=O',
 61: 'O=C1CN=C(c2ccccc2)c2cc(Cl)ccc2N1',
 62: 'O=C1Nc2ccc(Cl)cc2C(c2ccccc2)=NC1O',
 63: 'O=P1(NCCCl)OCCCN1CCCl',
 64: 'OCCOCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1'}

In [8]:
# 假设你的 dict 是如下
atom_scores = {3: 5.6, 1: 1.2, 4: 2.3, 2: 3.4}

# 按 key 排序
sorted_atom_scores = {k: atom_scores[k] for k in sorted(atom_scores)}

print(sorted_atom_scores)

{1: 1.2, 2: 3.4, 3: 5.6, 4: 2.3}

In [7]:
dirpath = '/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/somp/som_results'
filepathlist = os.listdir(dirpath)
substrates_new = []
enzymes_new = []
dicts_new = []

for filepath in filepathlist:
    idx = int(filepath.split('_')[0])
    substrates_new.append(dict_idx2sub[idx])
    enzyme = filepath.split('_')[1].split('.')[0]
    enzymes_new.append(enzyme)
    filepathfull = dirpath + '/' + filepath
    df = pd.read_csv(filepathfull)
    atomnums = df['Atom number'].to_list()
    ranks = df['Rang'].to_list()
    dict_atomidx2rank = dict(zip(atomnums,ranks))
    dict_atomidx2rank = {k: dict_atomidx2rank[k] for k in sorted(dict_atomidx2rank)}
    dicts_new.append(dict_atomidx2rank)

df_new = pd.DataFrame()
df_new['substrates'] = substrates_new
df_new['enzyme'] = enzymes_new
df_new['scores'] = dicts_new
df_new

,substrates,enzyme,scores
0,O=P1(NCCCl)OCCCN1CCCl,2C9,"{10: 1, 12: 2, 4: 3, 11: 4, 14: 5, 1: 6, 3: 7,..."
1,Clc1ccccc1CN1CCc2sccc2C1,UGT,"{9: 1, 1: 2, 13: 3, 11: 4, 5: 5, 14: 6, 4: 7, ..."
2,Cn1c(=O)c2c(ncn2C)n(C)c1=O,3A4,"{8: 1, 12: 2, 1: 3, 10: 4, 14: 5, 4: 6, 9: 7, ..."
3,Cc1cccc(C)c1OCC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)...,2C9,"{39: 1, 44: 2, 10: 3, 41: 4, 1: 5, 7: 6, 4: 7,..."
4,O=C(O)c1cc(O)c2c(c1)C(C1c3cc(C(=O)O)cc(O)c3C(=...,1A2,"{31: 1, 52: 2, 40: 3, 45: 4, 39: 5, 46: 6, 33:..."
...,...,...,...
385,CC(CN1c2ccccc2Sc2ccccc21)N(C)C,UGT,"{18: 1, 4: 2, 19: 3, 20: 4, 11: 5, 1: 6, 7: 7,..."
386,C[C@@H](Oc1cc(-c2cnn(C3CCNCC3)c2)cnc1N)c1c(Cl)...,3A4,"{2: 1, 20: 2, 14: 3, 16: 4, 26: 5, 3: 6, 6: 7,..."
387,CCCSc1nc(N[C@@H]2C[C@H]2c2ccc(F)c(F)c2)c2nnn([...,2D6,"{32: 1, 4: 2, 33: 3, 1: 4, 2: 5, 10: 6, 13: 7,..."
388,NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1,3A4,"{9: 1, 20: 2, 8: 3, 15: 4, 11: 5, 17: 6, 18: 7..."
389,Cc1cc2c(s1)Nc1ccccc1N=C2N1CCN(C)CC1,UGT,"{19: 1, 7: 2, 6: 3, 16: 4, 14: 5, 1: 6, 20: 7,..."

In [6]:
df = pd.read_csv('/home/datahouse1/raojingxin/myprojects/enzyme/metabolism/SOM_cases/somp/som_results/0_1A2.csv')
atomnums = df['Atom number'].to_list()
ranks = df['Rang'].to_list()
dict_atomidx2rank = dict(zip(atomnums,ranks))

    Atom number  Rang  Delta P
0            15     1    0.160
1            14     2    0.111
2            21     3    0.082
3             8     4    0.079
4            27     5    0.079
5             9     6    0.033
6            30     7    0.030
7            31     8    0.027
8            19     9   -0.026
9            28    10   -0.055
10           22    11   -0.069
11           11    12   -0.112
12           13    13   -0.112
13           24    14   -0.112
14           26    15   -0.112
15           17    16   -0.139
16            6    17   -0.142
17            5    18   -0.227
18           23    19   -0.287
19           18    20   -0.330
20           12    21   -0.360
21            1    22   -0.371
22           20    23   -0.391
23           16    24   -0.406
24           25    25   -0.412
25           10    26   -0.423
26            3    27   -0.432
27            7    28   -0.456
28            2    29   -0.515
29            4    30   -0.528
30           29    31   -0.575